Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2023-10, with the labels that each got.

#6843 bug/6445-theo-AndroidActionSheetTextCutoff
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-With QA

#6769 feature/6651-Dylan-userLoggedInApiPost
  VAMobile/src/store/slices/authSlice.ts
Labels: FE-With QA

#6782 Fix focus on error issue in Messaging
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
Labels: FE-With QA

#6886 Bump to v0.0.22 of mobile-components
  VAMobile/package.json
  VAMobile/yarn.lock
Labels: FE-With QA

#6888 bug/6587-theo-ModalPickerLinkColor
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
Labels: FE-With QA

#6733 feature/6410-theo-contact-info-React-Query
  VAMobile/src/api/contactInformation/deleteAddress.tsx
  VAMobile/src/api/contactInformation/deleteEmail.tsx
  VAMobile/src/api/contactInformation/deletePhoneNumber.tsx
  VAMobile/src/api/contactInformation/getContactInformation.tsx
  VAMobile/src/api/contactInformation/index.ts
  VAMobile/src/api/contactInformation/queryKeys.ts
  VAMobile/src/api/contactInformation/saveAddress.tsx
  VAMobile/src/api/contactInformation/saveEmail.tsx
  VAMobile/src/api/contactInformation/savePhoneNumber.tsx
  VAMobile/src/api/contactInformation/validateAddress.tsx
  VAMobile/src/api/queryClient.ts
  VAMobile/src/api/types/AddressData.ts
  VAMobile/src/api/types/ContactInformation.ts
  VAMobile/src/api/types/EmailData.ts
  VAMobile/src/api/types/PhoneData.ts
  VAMobile/src/api/types/index.ts
  VAMobile/src/components/Nametag/Nametag.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/RequestAppointments/AppointmentFlowSteps/ConfirmContactScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeStackScreens.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressSummary/AddressSummary.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressSummary/AddressSummary.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressValidation/AddressValidation.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressValidation/AddressValidation.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.test.tsx
  VAMobile/src/screens/OnboardingCarousel/OnboardingCarousel.test.tsx
  VAMobile/src/store/api/demo/mocks/contactInformation.json
  VAMobile/src/store/api/demo/profile.ts
  VAMobile/src/store/api/demo/store.ts
  VAMobile/src/store/api/types/PhoneData.ts
  VAMobile/src/store/api/types/UserData.ts
  VAMobile/src/store/api/types/index.ts
  VAMobile/src/store/slices/personalInformationSlice.test.ts
  VAMobile/src/store/slices/personalInformationSlice.ts
  VAMobile/src/testUtils.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/common.ts
  VAMobile/src/utils/personalInformation.tsx
  VAMobile/src/utils/tests/profile.tsx
Labels: FE-With QA

#6862 bug/6480-Dylan-ProperlyComparingDates
  VAMobile/src/utils/formattingUtils.ts
Labels: FE-With QA

#6889 bug/5036-theo-NotificationPreferenceToggles
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#6950 6736-chris-android-firefox-login-fix
  VAMobile/android/app/src/main/java/gov/va/mobileapp/native_modules/CustomTabsIntentModule.kt
Labels: FE-With QA

#6847 Feature/6412 dylan v2 user
  VAMobile/src/api/personalInformation/getPersonalInformation.tsx
  VAMobile/src/api/personalInformation/queryKeys.ts
  VAMobile/src/api/types/PersonalInformationData.ts
  VAMobile/src/api/types/index.ts
  VAMobile/src/components/Nametag/Nametag.test.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersOverviewScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersOverviewScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/screens/OnboardingCarousel/OnboardingCarousel.test.tsx
  VAMobile/src/screens/OnboardingCarousel/OnboardingCarousel.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.test.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.test.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/store/api/demo/mocks/personalInformation.json
  VAMobile/src/store/api/demo/mocks/profile.json
  VAMobile/src/store/api/demo/profile.ts
  VAMobile/src/store/api/demo/store.ts
  VAMobile/src/store/api/types/UserData.ts
  VAMobile/src/store/index.ts
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/store/slices/claimsAndAppealsSlice.test.ts
  VAMobile/src/store/slices/index.ts
  VAMobile/src/store/slices/personalInformationSlice.test.ts
  VAMobile/src/store/slices/personalInformationSlice.ts
  VAMobile/src/store/slices/secureMessagingSlice.ts
  VAMobile/src/testUtils.tsx
  VAMobile/src/utils/tests/profile.tsx
Labels: FE-With QA

#6905 Update SM to new MoVADS SegmentedControl
  VAMobile/src/components/MessageAlert.tsx
  VAMobile/src/components/SegmentedControl.test.tsx
  VAMobile/src/components/SegmentedControl.tsx
  VAMobile/src/components/index.ts
  VAMobile/src/constants/secureMessaging.ts
  VAMobile/src/screens/HealthScreen/SecureMessaging/CancelConfirmations/ComposeCancelConfirmation.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoFolderMessages/NoFolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/store/api/types/SecureMessagingData.ts
  VAMobile/src/store/slices/secureMessagingSlice.test.ts
  VAMobile/src/store/slices/secureMessagingSlice.ts
Labels: FE-With QA

#6982 bug/6980-theo-GenderIdentityNotLoading
  VAMobile/src/api/demographics/getGenderIdentityOptions.tsx
  VAMobile/src/api/types/DemographicsData.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
Labels: FE-Needs Review

#6992 bug/6985-chris-android-login-fix
  VAMobile/android/app/src/main/java/gov/va/mobileapp/native_modules/CustomTabsIntentModule.kt
Labels: FE-With QA, FE-Needs Review

#6863 feature/6804-Dylan-RXListEnhancementCopy
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHelp/PrescriptionHelp.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNoPrescriptions.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#6957 bug/5037-ClaimIconLargeFontNonScalingSize
  VAMobile/src/utils/claims.tsx
Labels: FE-With QA

#6973 bug/6907-Dylan-FixFillDateSortBy
  VAMobile/src/store/slices/prescriptionSlice.ts
Labels: FE-With QA

#7016 Remove unused dependencies
  VAMobile/package.json
  VAMobile/yarn.lock
Labels: FE-Needs Review

#6880 bug/5888-theo-AppointmentsError
  VAMobile/src/components/CommonErrorComponents/CallHelpCenter.tsx
  VAMobile/src/components/CommonErrorComponents/ErrorAlert.test.tsx
  VAMobile/src/components/CommonErrorComponents/ErrorAlert.tsx
  VAMobile/src/components/CommonErrorComponents/ErrorComponent.tsx
  VAMobile/src/components/CommonErrorComponents/index.ts
  VAMobile/src/constants/errors.ts
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/IndividualMessageErrorComponent.tsx
  VAMobile/src/store/slices/appointmentsSlice.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/errors.ts
Labels: FE-With QA

#6995 CU/5373-Dylan-DismissSnackbarOnNav
  VAMobile/src/constants/common.ts
Labels: FE-With QA

#6977 CU/6664-Dylan-UpdateDemoAppts
  VAMobile/src/store/api/demo/mocks/appointments.json
Labels: FE-With QA

#6643 CI e2e test automation and Android
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  .github/workflows/start_slack_thread.yml
  VAMobile/.detoxrc.json
  VAMobile/android/app/build.gradle
  VAMobile/android/version.properties
  VAMobile/detoxconfig.js
  VAMobile/e2e/environment.js
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/Payments.e2e.ts
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/env/test.env.ts
  VAMobile/ios/VAMobile.xcodeproj/project.pbxproj
  VAMobile/package.json
  VAMobile/src/store/api/demo/mocks/prescriptions.json
  VAMobile/yarn.lock
Labels: FE-With QA

#6991 bug/5107-Dylan-SnackbarScrollView
  VAMobile/src/components/SnackBar.tsx
Labels: FE-With QA

#6993 feature/5669-theo-dependabot
  .github/dependabot.yml
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-Needs Review

#7166 Feature/6930 tkd GitHub actions ios letters
  VAMobile/e2e/tests/Letters.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Needs Review
