Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2023-08, with the labels that each got.

#6430 bug/5400-Dylan-removeBackA11yLabel
  VAMobile/src/components/DescriptiveBackButton.tsx
Labels: FE-With QA

#5799 Detox-Add test for Appointments
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/ClickToCallPhoneNumber.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
Labels: FE-Needs Review

#6350 Add Detox Test for Disability Rating
  VAMobile/e2e/tests/DisabilityRatings.e2e.ts
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/ClickForActionLink.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
Labels: FE-Needs Review

#6451 Revert auth to use WebviewLogin on Android instead of Custom Tabs
  VAMobile/android/Gemfile.lock
  VAMobile/src/App.tsx
  VAMobile/src/screens/auth/LoaGate/LoaGate.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/screens/auth/WebviewLogin/WebviewLogin.test.tsx
  VAMobile/src/screens/auth/WebviewLogin/WebviewLogin.tsx
  VAMobile/src/screens/auth/WebviewLogin/index.ts
  VAMobile/src/utils/rnAuthSesson.tsx
Labels: FE-With QA

#6447 bug/1014-chris-direct-deposit-keyboard-nav
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
Labels: FE-With QA

#6443 bug/4702-Dylan-InlineErrorSelectAddress
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressValidation/AddressValidation.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#6431 bug/6015-Dylan-RemoveWCAGSpacingAlertBoxText
  VAMobile/src/components/AlertBox.tsx
  VAMobile/src/components/CommonErrorComponents/CallHelpCenter.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/NoVaccineRecords/NoVaccineRecords.tsx
Labels: FE-With QA

#6461 feature/6387-Dylan-ChangeConfirmedApptsToTagGreen
  VAMobile/src/utils/appointments.tsx
Labels: FE-With QA

#6468 bug/5965-theo-LettersFailedDownload
  VAMobile/src/screens/BenefitsScreen/Letters/BenefitSummaryServiceVerification/BenefitSummaryServiceVerification.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/GenericLetter/GenericLetter.tsx
Labels: FE-With QA

#6463 feature/6290-Dylan-EncouragedUpdateInformationalToWarningAlert
  VAMobile/src/components/EncourageUpdate.tsx
Labels: FE-With QA

#6305 feature/5667-theo-DeepLinking
  VAMobile/e2e/tests/PushNotifications.e2e.ts
  VAMobile/package.json
  VAMobile/src/App.test.tsx
  VAMobile/src/App.tsx
  VAMobile/src/components/NotificationManager/NotificationManager.tsx
  VAMobile/src/constants/linking.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/store/slices/notificationSlice.ts
  VAMobile/src/store/slices/secureMessagingSlice.ts
  VAMobile/yarn.lock
Labels: FE-With QA

#6477 bug/6362-chris-dynamic-dates-demo-mode
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/store/api/demo/store.ts
Labels: FE-With QA

#6448 feature/6316-Dylan-CleanUpCompPen
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
Labels: FE-With QA

#6474 feature/6162-Dylan-RXDefaultActive
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
Labels: FE-With QA

#6469 bug/6315-theo-RoutingNumberHelperText
  VAMobile/src/components/FormWrapper/FormWrapper.test.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#6462 bug/4977-Dylan-LandscapeNotchedBackgroundColor
  VAMobile/src/screens/OnboardingCarousel/GenericOnboarding/GenericOnboarding.tsx
  VAMobile/src/screens/SplashScreen/SplashScreen.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
Labels: FE-With QA

#6513 bug/6066-chris-message-details-failure-spacing
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/IndividualMessageErrorComponent.tsx
Labels: FE-With QA

#6503 bug/6292-theo-SendMessageReplyDraft
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
Labels: FE-With QA

#6526 bug/5988-Dylan-SnackbarDismissOnNavFromLettersLandingPage
  VAMobile/src/constants/common.ts
Labels: FE-With QA

#6464 feature/5966-Dylan-FindLocationAnalytics
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
Labels: FE-With QA

#6248 Add Detox UI test for Contact Info
  VAMobile/e2e/tests/ContactInformation.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/AccordionCollapsible.tsx
  VAMobile/src/components/CollapsibleAlert.tsx
  VAMobile/src/components/FormWrapper/FormFields/RadioGroup.tsx
  VAMobile/src/components/FormWrapper/FormFields/VASelector.tsx
  VAMobile/src/components/FormWrapper/FormFields/VATextInput.tsx
  VAMobile/src/components/Templates/FullScreenSubtask.tsx
  VAMobile/src/components/Templates/HeaderBanner.tsx
  VAMobile/src/components/Templates/LargePanel.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressValidation/AddressValidation.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/HowWillYouScreen/HowWillYouScreen.tsx
Labels: FE-Needs Review

#6467 bug/4985-theo-DisabilityRatingsAPICall
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
Labels: FE-With QA

#6472 feature/6355-theo-DeepLinkingAnalytics
  VAMobile/src/components/NotificationManager/NotificationManager.tsx
  VAMobile/src/constants/analytics.ts
Labels: FE-With QA

#6516 bug/5785-Dylan-NoClosedClaimsAppealsCopy
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppeals/NoClaimsAndAppeals.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppeals/NoClaimsAndAppeals.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#6466 feature/6393-Dylan-SMAnalytics
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Folders/Folders.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Inbox/Inbox.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoFolderMessages/NoFolderMessages.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/Attachments/Attachments.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessageButton/StartNewMessageButton.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessageButton/StartNewMessageButton.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/store/slices/secureMessagingSlice.ts
  VAMobile/src/utils/secureMessaging.tsx
Labels: FE-With QA

#6529 bug/6270-chris-ddl-auth-services-check
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/store/api/demo/mocks/profile.json
  VAMobile/src/store/api/types/UserData.ts
  VAMobile/src/store/slices/authorizedServicesSlice.ts
Labels: FE-With QA

#6568 Update What's New for 2.10 release
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
Labels: FE-Changes Requested

#6540 Updated build tools version to 33
  VAMobile/android/build.gradle
Labels: FE-With QA

#6578 Revert dylan rx active
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
Labels: FE-With QA

#6494 feature/6182-ApptAnalytics
  VAMobile/src/components/AccordionCollapsible.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/components/SegmentedControl.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PendingAppointmentCancelButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/store/slices/appointmentsSlice.ts
  VAMobile/src/utils/appointments.tsx
Labels: FE-With QA

#6525 feature/6429-Dylan-InvalidRoutingNumberValidation
  VAMobile/e2e/tests/DirectDeposit.e2e.ts
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#6524 bug/5854-Dylan-AppointmentCalendarGeolocationAddress
  VAMobile/ios/Podfile.lock
  VAMobile/ios/Pods/Local Podspecs/react-native-notifications.podspec.json
  VAMobile/ios/Pods/Manifest.lock
  VAMobile/ios/RNCalendar.m
  VAMobile/ios/RNCalendar.swift
  VAMobile/src/components/ClickForActionLink.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/utils/rnCalendar.tsx
Labels: FE-With QA

#6582 bug/6168-chris-actionsheet-darkmode
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-With QA

#6589 feature/Binny-5706-CheckInFeatureFlag
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/CheckIn/ConfirmContactInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-With QA

#6613 Re-implement Custom tabs. Fix app switcher behavior.
  VAMobile/android/app/src/main/AndroidManifest.xml
  VAMobile/android/app/src/main/java/gov/va/mobileapp/native_modules/CustomTabsIntentModule.kt
  VAMobile/src/App.tsx
  VAMobile/src/screens/auth/LoaGate/LoaGate.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/screens/auth/WebviewLogin/WebviewLogin.test.tsx
  VAMobile/src/screens/auth/WebviewLogin/WebviewLogin.tsx
  VAMobile/src/screens/auth/WebviewLogin/index.ts
  VAMobile/src/utils/rnAuthSesson.tsx
Labels: FE-With QA

#6590 Deep linking documentation
  VAMobile/documentation/docs/Engineering/FrontEnd/PushNotifications/DeepLinking.md
  VAMobile/documentation/docs/Engineering/FrontEnd/PushNotifications/_category_.json
Labels: FE-Needs Review
