Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2023-12, with the labels that each got.

#7199 feature/6939-Dylan-e2eAndroidSlack
  .github/workflows/e2e_android.yml
Labels: FE-With QA

#7303 Bug/binny 7298 required fields for waygates
  VAMobile/src/components/WaygateWrapper.tsx
Labels: FE-With QA

#7200 feature/6933-Dylan-e2eiOSSlackNotifications
  .github/workflows/e2e_ios.yml
Labels: FE-Needs Review

#7431 bug/7259-theo-AFBannerScroll
  VAMobile/src/components/Templates/CategoryLanding.tsx
  VAMobile/src/components/Templates/FeatureLandingAndChildTemplate.tsx
  VAMobile/src/components/Templates/FullScreenSubtask.tsx
  VAMobile/src/components/Templates/LargePanel.tsx
  VAMobile/src/components/WaygateWrapper.tsx
Labels: FE-Changes Requested

#7474 feature/7473-detox-testRail-integration-script-logic-fix
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-Needs Review

#7416 feature/7256-Dylan-InPersonNonCPorCoommunityCareApptsCards
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointments.test.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/appointments.tsx
Labels: FE-With QA

#7408 bug/7237-chris-vaccine-records-maintenance-window
  VAMobile/src/store/api/types/Errors.ts
Labels: FE-With QA

#7491 feature/7490-theo-appointment-deep-link-analytics
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
Labels: FE-Needs Review

#7443 bug/5034-chris-claims-file-upload-font-size-fix
  VAMobile/src/components/PhotoAdd.tsx
  VAMobile/src/components/PhotoPreview.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
Labels: FE-With QA

#7454 Wait until focus to display AlertBox
  VAMobile/src/components/WaygateWrapper.tsx
Labels: FE-With QA

#7507 bug/7506-rachael-detox-appointments-failure
  VAMobile/e2e/tests/Appointments.e2e.ts
Labels: FE-With QA

#7469 bug/6619-Liz-select-list-header-font-size
  VAMobile/src/components/SelectionList/SelectionList.tsx
Labels: FE-With QA

#7415 CU/7414-Liz-disability-rating-downtime-fix
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/store/slices/errorSlice.test.ts
Labels: FE-With QA

#7481 Enhancement/5264 - Hasan Ahmed - Swap Large List Nav for List Rows on Personal Information Screen
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
Labels: FE-With QA

#7553 bug/7552-rachael-detox-android-personal-info
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/HowDoIUpdateScreen/HowDoIUpdateScreen.tsx
Labels: FE-With QA

#7505 feature/7266-detox-rachael-claims-expansion
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/store/api/demo/mocks/claims.json
Labels: FE-With QA

#7535 bug/chris-7511-back-button-chevron-fix
  VAMobile/src/components/DescriptiveBackButton.tsx
Labels: FE-With QA

#7520 feature/7499-rachael-detox-text-resizing
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequestDetails/FileRequestDetails.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersOverviewScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentsScreen.tsx
Labels: FE-With QA

#7495 feature/7379-theo-HomeScreenAppointmentsModule
  VAMobile/src/constants/linking.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/store/api/types/AppointmentData.ts
  VAMobile/src/store/slices/appointmentsSlice.ts
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#7510 bug/7335-chris-vaccines-groupname-null-fix
  VAMobile/src/store/slices/vaccineSlice.test.ts
  VAMobile/src/store/slices/vaccineSlice.ts
Labels: FE-With QA

#7557 feature/7381-theo-HomeScreenModulePrescriptions
  VAMobile/src/constants/linking.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.test.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/store/api/types/PrescriptionData.ts
  VAMobile/src/store/slices/prescriptionSlice.ts
  VAMobile/src/translations/en/common.json
Labels: FE-Needs Review

#7583 bug/7582-rachael-detox-navigation-appeals
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
Labels: FE-Needs Review
