Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-11, with the labels that each got.

#10081 Doc Site: Update Figma instructions for Experience Teams
  VAMobile/documentation/design/About/designers.md
Labels: FE-With QA

#10043 CU/10042-rachael-detox-change-send-to-testRail-job
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  .github/workflows/update_testrail_results.yml
Labels: FE-Ready to Merge

#9864 feature/9265-Binny-PushLoginFlowChanges
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/App.tsx
  VAMobile/src/components/NotificationManager/NotificationManager.tsx
  VAMobile/src/screens/BiometricsPreferenceScreen/BiometricsPreferenceScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.tsx
  VAMobile/src/screens/auth/BiometricsPreferenceScreen/BiometricsPreferenceScreen.test.tsx
  VAMobile/src/screens/auth/BiometricsPreferenceScreen/BiometricsPreferenceScreen.tsx
  VAMobile/src/screens/auth/BiometricsPreferenceScreen/index.ts
  VAMobile/src/screens/auth/RequestNotifications/RequestNotificationsScreen.test.tsx
  VAMobile/src/screens/auth/RequestNotifications/RequestNotificationsScreen.tsx
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10065 feature/9969-EFolderAPIs
  VAMobile/src/api/claimsAndAppeals/downloadEFolderDocument.tsx
  VAMobile/src/api/claimsAndAppeals/getEFolderDocuments.tsx
  VAMobile/src/api/claimsAndAppeals/index.ts
  VAMobile/src/api/claimsAndAppeals/queryKeys.ts
  VAMobile/src/api/types/ClaimsAndAppealsData.ts
  VAMobile/src/store/api/demo/mocks/claims.json
Labels: FE-With QA

#9920 Feature/9764 update medication wording for claim exam
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/env/constant.env
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/ClaimExamAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/ClaimExamAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentMedicationWording.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/env.ts
Labels: FE-Ready to Merge

#10119 Revert "Adding a page for accessible research sessions"
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/a11y-research-session-help.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/index.md
Labels: FE-Ready to Merge

#10032 bug/7801-SMButtonLinkUpdates
  VAMobile/src/components/Menu/MenuView.tsx
Labels: FE-Ready to Merge

#10034 bug/7807-RXButtonLinkUpdates
  VAMobile/src/components/LabelTag.tsx
  VAMobile/src/components/MultiTouchCard.test.tsx
  VAMobile/src/components/MultiTouchCard.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionCommon/RefillTag.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
Labels: FE-Ready to Merge

#10125 Chore/9993-Usei18nInUnitTests-Home-1
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
Labels: FE-Ready to Merge

#10087 9851-TKD-testID-detox-utils-part-one
  VAMobile/e2e/tests/Onboarding.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#10122 CU-10121-add-sarah-uber-to-release-coordination-thread-quart-new-pm-github-update
  .github/ISSUE_TEMPLATE/Post_RC_Code_Change.md
  .github/ISSUE_TEMPLATE/release_ticket.md
  .github/workflows/release_branch_issue.yml
Labels: FE-Ready to Merge

#9544 feature/9348-DemoModeAPIOverrides
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeStackScreens.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/OverrideApiScreen.tsx
  VAMobile/src/store/api/api.ts
  VAMobile/src/store/slices/demoSlice.ts
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10120 bug/10117-rachael-detox-fix-onboarding-after-push-notifications
  .github/workflows/e2e_detox_mapping.yml
  VAMobile/e2e/tests/Onboarding.e2e.ts
Labels: FE-Ready to Merge

#10140 chore/9994-Usei18nInUnitTests-Home-2
  VAMobile/src/screens/HomeScreen/ContactVAScreen/ContactVAScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.test.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineScreen.test.tsx
Labels: FE-With QA

#10044 Automation/6808-chanel-create-system-for-updating-names-on-release-tickets
  .github/workflows/release_branch_issue.yml
Labels: devops, FE-With QA, QA and Release

#10156 CU/9849-TKD-detox-Nav-bytext-removal
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#10169 Automation/9790-chanel-add-brea11y-narin-in-lists-of-reviewers
  .github/workflows/qa_required_approvals.yml
Labels: devops, QA and Release, FE-Ready to Merge

#10061 bug/9925-Android15Biometrics
  VAMobile/package.json
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/store/slices/authSlice.sis.test.ts
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/utils/auth.ts
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#10139 CU/Binny-10138-BypassPhoneOnAF
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/WaygateWrapper.tsx
Labels: FE-Ready to Merge

#10157 chore/9995-Usei18nInUnitTests-Home-3
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/IncorrectServiceInfo/IncorrectServiceInfo.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/NoMilitaryInformationAccess.test.tsx
Labels: FE-Ready to Merge

#9889 CU/9464-Chika-ChangeSomeComponentsOutOfLinkAndButtonRoles
  VAMobile/patches/@department-of-veterans-affairs+mobile-component-library+0.21.0.patch
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.test.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/components/FormWrapper/FormFields/RadioGroup.test.tsx
  VAMobile/src/components/FormWrapper/FormFields/RadioGroup.tsx
  VAMobile/src/components/FormWrapper/FormFields/VASelector.tsx
  VAMobile/src/components/RadioGroupModal.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.test.tsx
Labels: FE-Ready to Merge, FE-Needs Review

#9199 feature/7573-UpdateAppColorsToComponentLibrary
  VAMobile/src/components/ActivityButton.tsx
  VAMobile/src/components/AnnouncementBanner.tsx
  VAMobile/src/components/BackButton.tsx
  VAMobile/src/components/Box.tsx
  VAMobile/src/components/DescriptiveBackButton.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/PickerList.tsx
  VAMobile/src/components/IconWithText/IconWithText.tsx
  VAMobile/src/components/LargeNavButton.tsx
  VAMobile/src/components/LoadingComponent/LoadingComponent.tsx
  VAMobile/src/components/Menu/Menu.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/components/NavigationTabBar.tsx
  VAMobile/src/components/PhotoAdd.tsx
  VAMobile/src/components/SnackBar.tsx
  VAMobile/src/components/Templates/HeaderBanner.tsx
  VAMobile/src/components/TextView.tsx
  VAMobile/src/components/VABulletList.tsx
  VAMobile/src/constants/screens.ts
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/OnboardingCarousel/GenericOnboarding/GenericOnboarding.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/screens/auth/LoginScreen/DemoAlert.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/VAColors.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-Ready to Merge

#10192 CU/10085 TKD more bytext removal in detox utils
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/MilitaryInformation.e2e.ts
  VAMobile/e2e/tests/ProfileScreen.e2e.ts
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/Templates/CategoryLanding.tsx
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentsScreen.tsx
Labels: FE-Ready to Merge

#10127 bug/9900-ClaimFileRequestBottomSpacing
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/SelectFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.tsx
Labels: FE-Ready to Merge

#10143 bug/10115-VALogoResizing
  VAMobile/src/components/VALogo/VALogo.tsx
Labels: FE-Ready to Merge

#10166 Spike binny in app feedback
  VAMobile/env/constant.env
  VAMobile/env/test.env.ts
  VAMobile/src/App.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/DetailsTextSections.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppFeedbackScreen/InAppFeedbackScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/env.ts
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-Ready to Merge

#10212 Adding MCAG overview and guidance
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/MCAG/_category_.json
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/MCAG/additional-guidance.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/MCAG/index.md
Labels: FE-Ready to Merge

#10215 doc/removing QART lead references
  VAMobile/documentation/docs/Operations/Updating the doc site/Gettingsetup.md
  VAMobile/documentation/docs/Operations/Updating the doc site/index.md
Labels: FE-Ready to Merge

#10066 feature/9970-EfolderFilesUsable
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimFiles/ClaimFiles.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimFiles/ClaimFiles.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10067 feature/9971-EFolderViewAnalytics
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
Labels: FE-Ready to Merge

#10145 bug/10113-FixRefillConfirmationCheckmarkColor
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
Labels: FE-Ready to Merge

#9916 feature/9816-EvenMoreIconMigrations
  VAMobile/documentation/docs/Flagship design library/Components/Uncategorized/VAIcon.mdx
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/commonIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/webviewIcons.md
  VAMobile/src/components/BackButton.test.tsx
  VAMobile/src/components/BackButton.tsx
  VAMobile/src/components/BaseListItem.tsx
  VAMobile/src/components/DescriptiveBackButton.tsx
  VAMobile/src/components/InlineTextWithIcons.test.tsx
  VAMobile/src/components/LinkRow.tsx
  VAMobile/src/components/MessageList.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/components/Pagination.tsx
  VAMobile/src/components/PhotoAdd.tsx
  VAMobile/src/components/PhotoUpload.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
  VAMobile/src/components/VAIcon/svgs/ChevronLeft.svg
  VAMobile/src/components/VAIcon/svgs/ChevronRight.svg
  VAMobile/src/screens/BenefitsScreen/Letters/GenericLetter/GenericLetter.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/WebviewScreen/WebviewScreen.tsx
  VAMobile/src/styles/themes/standardTheme.ts
  VAMobile/src/utils/hooks/headerStyles.tsx
Labels: FE-Ready to Merge

#10201 Add Postman collection documentation
  VAMobile/documentation/docs/Engineering/BackEnd/Testing/Postman.md
Labels: FE-With QA

#10229 Automation/10228-chanel-update-sarah-on-release-coordination-thread-and-fic-release-ticket-number
  .github/workflows/release_branch_issue.yml
Labels: FE-Ready to Merge

#10202 Verify builds work before PRs are merged
  .github/workflows/code_checks.yml
  .github/workflows/native_build_check_android.yml
  .github/workflows/native_build_check_android_reusable.yml
  .github/workflows/native_build_check_android_skip.yml
  .github/workflows/native_build_check_ios.yml
  .github/workflows/native_build_check_ios_reusable.yml
  .github/workflows/native_build_check_ios_skip.yml
  VAMobile/android/fastlane/Fastfile
  VAMobile/ios/fastlane/Fastfile
Labels: FE-Changes Requested, FE-Ready to Merge

#10220 CU/10064-Chika-UpdateFirstSignInPageContent
  VAMobile/e2e/tests/SignIn.e2e.ts
  VAMobile/src/screens/auth/LoaGate/LoaGate.test.tsx
  VAMobile/src/screens/auth/LoaGate/LoaGate.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10259 Adding Doc on how to Handle Release Tickets Failure
  VAMobile/documentation/docs/Engineering/DevOps/Automation Code Docs/GitHub Actions/ReleaseIssues.md
Labels: devops, FE-Changes Requested, QA and Release, FE-Ready to Merge

#10226 Add PR Status checks for App Store Requirements
  .github/workflows/app_store_checks_apple.yml
  .github/workflows/app_store_checks_google.yml
  .github/workflows/check_max_size.yml
Labels: devops, FE-With QA

#10243 bug/10242-Binny-VALogoCutOff
  VAMobile/src/components/VALogo/VALogo.tsx
Labels: FE-Ready to Merge

#10245 bug/10137-Binny-FixOnboardingA11yHint
  VAMobile/src/screens/OnboardingCarousel/OnboardingCarousel.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10264 Migrating remote config docs
  VAMobile/documentation/docs/Engineering/FrontEnd/RemoteConfig/index.md
Labels: FE-With QA

#10262 CU/10203 tkd organize detox constants
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#10106 CU/10094-Chika-UpgradeMobileDesignLibraryAndUpdateFlag
  VAMobile/package.json
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentLocation.tsx
  VAMobile/src/utils/remoteConfig.ts
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#10268 cleanup workflows
  .github/workflows/app_store_checks_apple.yml
  .github/workflows/app_store_checks_google.yml
  .github/workflows/check_max_size.yml
  .github/workflows/native_build_check_android.yml
Labels: devops, FE-Ready to Merge

#10271 update what's new
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
Labels: FE-Ready to Merge

#10269 Automation - Update start_slack_thread to paginate search for channel id
  .github/workflows/start_slack_thread.yml
Labels: FE-Ready to Merge

#10277 Update Postman.md
  VAMobile/documentation/docs/Engineering/BackEnd/Testing/Postman.md
Labels: FE-With QA

#10278 embed link fix attempt
  VAMobile/documentation/docs/UX/Foundations/Information-Architecture.md
Labels: FE-Ready to Merge

#10247 bug/9268-Binny-PutSettingsOnProfileAlways
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
Labels: FE-Ready to Merge
