Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-05, with the labels that each got.

#8278 bug/8051-Dylan-DemoDirectDepositFix
  VAMobile/e2e/tests/DirectDeposit.e2e.ts
  VAMobile/src/api/directDeposit/updateBankInfo.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
Labels: FE-Ready to Merge

#8489 feature/8428-chris-update-subtask-headings
  VAMobile/src/components/Templates/FullScreenSubtask.tsx
Labels: FE-Ready to Merge

#8513 Add documentation on design tokens
  VAMobile/documentation/design/Foundation/Design tokens/Color.md
  VAMobile/documentation/design/Foundation/Design tokens/Overview.md
  VAMobile/documentation/design/Foundation/Design tokens/index.md
  VAMobile/documentation/design/Foundation/Overview.md
  VAMobile/documentation/design/Foundation/index.md
  VAMobile/documentation/design/intro.md
  VAMobile/documentation/static/img/design-system/tokens-component.png
  VAMobile/documentation/static/img/design-system/tokens-primitive.png
  VAMobile/documentation/static/img/design-system/tokens-semantic-alert.png
  VAMobile/documentation/static/img/design-system/tokens-semantic.png
Labels: FE-With QA

#8474 bug/8458-chris-va-gov-voiceover-fix
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/TakePhotos.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/a11yLabel/va.tsx
Labels: FE-Ready to Merge

#8027 CU/7736-Dylan-SMReactQueryMigration
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/src/api/secureMessaging/deleteMessage.tsx
  VAMobile/src/api/secureMessaging/downloadFileAttachment.tsx
  VAMobile/src/api/secureMessaging/getFolderMessages.tsx
  VAMobile/src/api/secureMessaging/getFolders.tsx
  VAMobile/src/api/secureMessaging/getMessage.tsx
  VAMobile/src/api/secureMessaging/getMessageRecipients.tsx
  VAMobile/src/api/secureMessaging/getMessageSignature.tsx
  VAMobile/src/api/secureMessaging/getThread.tsx
  VAMobile/src/api/secureMessaging/index.ts
  VAMobile/src/api/secureMessaging/moveMessage.tsx
  VAMobile/src/api/secureMessaging/queryKeys.ts
  VAMobile/src/api/secureMessaging/saveDraft.tsx
  VAMobile/src/api/secureMessaging/sendMessage.tsx
  VAMobile/src/api/types/SecureMessagingData.ts
  VAMobile/src/api/types/index.ts
  VAMobile/src/components/MessageAlert.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/HealthScreen.test.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CancelConfirmations/ComposeCancelConfirmation.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CancelConfirmations/ComposeCancelConfirmation.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Folders/Folders.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Folders/Folders.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Inbox/Inbox.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Inbox/Inbox.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoFolderMessages/NoFolderMessages.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoFolderMessages/NoFolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/store/api/demo/mocks/secureMessaging.json
  VAMobile/src/store/api/demo/secureMessaging.ts
  VAMobile/src/store/api/demo/store.ts
  VAMobile/src/store/api/types/index.ts
  VAMobile/src/store/index.ts
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/store/slices/index.ts
  VAMobile/src/store/slices/secureMessagingSlice.test.ts
  VAMobile/src/store/slices/secureMessagingSlice.ts
  VAMobile/src/testUtils.tsx
  VAMobile/src/translations/en/functions.ts
  VAMobile/src/utils/hooks/index.tsx
  VAMobile/src/utils/secureMessaging.tsx
Labels: FE-Ready to Merge

#8481 bug/8432-theo-ReactQueryMaintenanceWindows
  VAMobile/src/api/appointments/getAppointments.tsx
  VAMobile/src/api/authorizedServices/getAuthorizedServices.tsx
  VAMobile/src/api/claimsAndAppeals/getClaimsAndAppeals.tsx
  VAMobile/src/api/decisionLetters/getDecisionLetters.tsx
  VAMobile/src/api/disabilityRating/getDisabilityRating.tsx
  VAMobile/src/api/militaryService/getServiceHistory.tsx
  VAMobile/src/api/prescriptions/getPrescriptions.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/store/slices/errorSlice.ts
  VAMobile/src/testUtils.tsx
Labels: FE-Ready to Merge

#8519 "Updating the App Stores" a11y + content updates
  VAMobile/documentation/docs/Operations/Updating the App Stores.md
Labels: FE-Ready to Merge

#8526 bug/8525-Dylan-FixedNotificationLinkingSMRQ
  VAMobile/src/constants/linking.tsx
Labels: FE-Ready to Merge

#8508 bug/8507-Dylan-FixWhatsNewAnalytic
  VAMobile/src/components/WhatsNew.tsx
Labels: FE-Ready to Merge

#8547 bug/revert-8081-run-detox-per-PR
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-Ready to Merge

#8403 feature/8134-Chika-UpdateHealthScreenWithCernerAlert
  VAMobile/src/screens/HealthScreen/HealthHelp/HealthHelp.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/styles/themes/standardTheme.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/waygateConfig.ts
Labels: FE-Ready to Merge

#8295 feature/7688-chris-use-link-component-benefits
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/package.json
  VAMobile/src/components/ClickForActionLinkDeprecated.test.tsx
  VAMobile/src/components/ClickForActionLinkDeprecated.tsx
  VAMobile/src/components/ClickToCallPhoneNumberDeprecated.tsx
  VAMobile/src/components/LinkWithAnalytics.tsx
  VAMobile/src/components/MessageAlert.tsx
  VAMobile/src/components/index.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/TakePhotos.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/WhatDoIDoIfDisagreement/WhatDoIDoIfDisagreement.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/WhatDoIDoIfDisagreement/WhatDoIDoIfDisagreement.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/BenefitSummaryServiceVerification/BenefitSummaryServiceVerification.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoFolderMessages/NoFolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/TermsAndConditions/TermsAndConditions.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/TermsAndConditions/TermsAndConditions.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/WhatToKnowScreen/WhatToKnowScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/HowDoIUpdateScreen/HowDoIUpdateScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/HowDoIUpdateScreen/HowDoIUpdateScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/SandboxScreen/CommonComponentWhiteList.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/SandboxScreen/SandboxScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineNumbers/VeteransCrisisLineNumbers.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineScreen.tsx
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#8356 feature/8183-theo-CategoryandHomeScreenRefresh
  VAMobile/src/api/appointments/cancelAppointment.tsx
  VAMobile/src/api/appointments/getAppointments.tsx
  VAMobile/src/api/claimsAndAppeals/getClaimsAndAppeals.tsx
  VAMobile/src/api/prescriptions/getPrescriptions.tsx
  VAMobile/src/api/secureMessaging/getFolders.tsx
  VAMobile/src/constants/common.ts
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/store/slices/authSlice.ts
Labels: FE-With QA

#8518 Some documentation accessibility fixes
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/ContinuousIntegrationAndDeployment.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/Endpoint Creation Checklist.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/FeatureFlagging.md
  VAMobile/documentation/docs/Engineering/BackEnd/Monitoring/Statsd.md
  VAMobile/documentation/docs/Engineering/BackEnd/Testing/StagingInstances.md
  VAMobile/documentation/src/components/HomepageFeatures.tsx
Labels: FE-With QA

#8298 feature/7937-theo-ActivitySectionErrorCases
  VAMobile/env/constant.env
  VAMobile/env/test.env.ts
  VAMobile/src/components/CategoryLandingAlert.tsx
  VAMobile/src/components/index.ts
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/env.ts
Labels: FE-With QA

#8552 bug/Chika-8537-Six-VeteranStatusCardSpacing
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
Labels: FE-With QA

#8554 bug/Binny-8532-CernerWarningAlwaysHSP2
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-With QA

#8553 Bug/binny 8537 one spacing fix hsp2
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-With QA

#8556 bug/Binny-8537-Four-CatSpacingFix
  VAMobile/src/components/Templates/CategoryLanding.tsx
Labels: FE-With QA

#8555 bug/Binny-8537-Three-BitterHeadingPixelChangeHSP2
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-With QA

#8557 bug/8537-theo-Eight-ServiceHistoryAPICall
  VAMobile/src/components/Nametag/Nametag.tsx
Labels: FE-With QA

#8559 bug/8537-Ten-theo-UnauthorizedAPICalls
  VAMobile/src/api/authorizedServices/getAuthorizedServices.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
Labels: FE-Needs Review

#8560 Update downtime hooks to use constants
  VAMobile/src/api/appointments/getAppointments.tsx
  VAMobile/src/api/claimsAndAppeals/getClaimsAndAppeals.tsx
  VAMobile/src/api/disabilityRating/getDisabilityRating.tsx
  VAMobile/src/api/letters/getLetterBeneficiaryData.tsx
  VAMobile/src/api/militaryService/getServiceHistory.tsx
  VAMobile/src/api/prescriptions/getPrescriptions.tsx
  VAMobile/src/api/secureMessaging/getFolders.tsx
Labels: FE-With QA

#8521 feature/8217-Chanel-Accessibility-checks-into-CI-documentation-site-new
  .github/workflows/documentation_accessibility_checks.yml
Labels: FE-Ready to Merge

#8512 feature/8511-theo-IgnoreMinorUpdates
  .github/dependabot.yml
Labels: FE-With QA

#8569 bug/Binny-8537-Eleven-IssueWithCategoryTitles
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-With QA

#8566 Slim down mobile datadog docs to not be redundant with datadogs own docs
  VAMobile/documentation/docs/Engineering/BackEnd/Monitoring/DataDog.md
  VAMobile/documentation/static/img/backend/datadog-add-widgets.png
  VAMobile/documentation/static/img/backend/datadog-alert-message.png
  VAMobile/documentation/static/img/backend/datadog-alert-metric.png
  VAMobile/documentation/static/img/backend/datadog-alert-notify.png
  VAMobile/documentation/static/img/backend/datadog-alert-threshold.png
  VAMobile/documentation/static/img/backend/datadog-aws-integration.png
  VAMobile/documentation/static/img/backend/datadog-create-graphs-1.png
  VAMobile/documentation/static/img/backend/datadog-create-graphs-2.png
  VAMobile/documentation/static/img/backend/datadog-create-graphs-3.png
  VAMobile/documentation/static/img/backend/datadog-create-graphs-4.png
  VAMobile/documentation/static/img/backend/datadog-example-graph-query.png
  VAMobile/documentation/static/img/backend/datadog-example-graph.png
  VAMobile/documentation/static/img/backend/datadog-formula-graph.png
  VAMobile/documentation/static/img/backend/datadog-metrics-explorer.png
  VAMobile/documentation/static/img/backend/datadog-mobile-api-dashboard.png
Labels: FE-Ready to Merge

#8568 Update On-Call documentation
  VAMobile/documentation/docs/Engineering/BackEnd/Monitoring/OnCallProcedure.md
Labels: FE-With QA, FE-Changes Requested

#8551 bug/8550-rachael-detox-nightly-errors
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/ContactInformation.e2e.ts
  VAMobile/e2e/tests/DirectDeposit.e2e.ts
  VAMobile/e2e/tests/MilitaryInformation.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
Labels: FE-With QA

#8585 Fixed headings on the design system home screen
  VAMobile/documentation/design/About/Contributing to the design system/contributing-to-the-design-system.md
  VAMobile/documentation/design/About/Contributing to the design system/writing-component-documentation.md
  VAMobile/documentation/design/intro.md
Labels: FE-With QA

#8460 CU/7360-chris-loading-error-usage-improvement
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineDetails/VaccineDetailsScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineList/VaccineListScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.tsx
Labels: FE-Ready to Merge

#8587 bug/8578-Five-MaintenanceWindowCheckForAppeals
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-Ready to Merge

#8599 bug/8578-Three-DeepLinkOptimizations
  VAMobile/src/api/facilities/getFacilitiesInfo.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
Labels: FE-With QA

#8601 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: FE-Ready to Merge

#8454 bug/8447-Dylan-RQNonGenericErrors
  VAMobile/src/components/CommonErrorComponents/ErrorComponent.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimLettersScreen/ClaimLettersScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/BenefitSummaryServiceVerification/BenefitSummaryServiceVerification.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/GenericLetter/GenericLetter.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersListScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersListScreen.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineList/VaccineListScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.tsx
Labels: FE-Ready to Merge

#8590 Update epic.md
  .github/ISSUE_TEMPLATE/epic.md
Labels: FE-Ready to Merge

#8602 Create External Bug Submission Template.md
  .github/ISSUE_TEMPLATE/External Bug Submission Template.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: FE-With QA

#8619 feature/Binny-8570-HomeScreenEndpointLoadTimes
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-Ready to Merge

#8626 CU/8368-rachael-detox-clean-up-leaving-app-instance
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/Cerner.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/DisabilityRatings.e2e.ts
  VAMobile/e2e/tests/Letters.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/e2e/tests/VeteransCrisisLine.e2e.ts
Labels: FE-Ready to Merge

#8623 8578-Chika-Seven-AboutYouSectionSpacing
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-With QA

#8639 bug/Binny-8578-One-VAPronounciationFixes
  VAMobile/src/components/AnnouncementBanner.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-Ready to Merge

#8647 Merge develop into feature-xl/HomeScreenPersonalization2 (5/15)
  .github/ISSUE_TEMPLATE/External Bug Submission Template.md
  .github/ISSUE_TEMPLATE/bug-report.md
  VAMobile/android/Gemfile.lock
  VAMobile/documentation/docs/App Features/Availability Framework/Availability Framework.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/DirectoryLayout.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/Endpoint Creation Checklist.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/FeatureFlagging.md
  VAMobile/documentation/docs/Engineering/BackEnd/Features/MaintenanceWindows.md
  VAMobile/documentation/docs/Engineering/BackEnd/Testing/ApiTokens.md
  VAMobile/documentation/docs/Engineering/DevOps/Automation Code Docs/GitHub Actions/Overview.md
  VAMobile/documentation/docs/Engineering/FrontEnd/AccessibilityInformation.md
  VAMobile/documentation/docs/Engineering/FrontEnd/DowntimeMessages.md
  VAMobile/documentation/docs/Engineering/FrontEnd/PushNotifications/DeepLinking.md
  VAMobile/documentation/docs/Flagship design library/Components/Overview.md
  VAMobile/documentation/docs/Flagship design library/Content/content-style-guide.md
  VAMobile/documentation/docs/Operations/Maintenance Windows.md
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/Cerner.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/DisabilityRatings.e2e.ts
  VAMobile/e2e/tests/Letters.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/e2e/tests/VeteransCrisisLine.e2e.ts
  VAMobile/ios/Gemfile.lock
  VAMobile/ios/Podfile.lock
  VAMobile/ios/VAMobile.xcodeproj/project.pbxproj
  VAMobile/package.json
  VAMobile/yarn.lock
Labels: FE-With QA

#8646 Update epic.md
  .github/ISSUE_TEMPLATE/epic.md
Labels: FE-With QA

#8596 feature/8502-chris-appointments-list-view-updates
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredAppointmentType.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointments.test.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/standardTheme.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/appointments.tsx
Labels: FE-Ready to Merge

#8655 doc/7601-OS Version support documentation
  VAMobile/documentation/docs/QA/Compatibility.md
  VAMobile/documentation/docs/QA/index.md
Labels: documentation, QA and Release, FE-Ready to Merge

#8663 bug/8662-Dylan-ProfileScreenInfiniteLoading
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
Labels: FE-Ready to Merge

#8656 feature/Binny-8652-ChangingHomeScreenHeaderFont
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-With QA

#8249 feature/8195-rachael-detox-run-per-feature-nav-af
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  VAMobile/.detoxrc.json
  VAMobile/detoxconfig.js
  VAMobile/documentation/docs/Engineering/FrontEnd/PushNotifications/DeepLinking.md
  VAMobile/documentation/docs/QA/Automation/AddingNewFeatures.md
  VAMobile/documentation/docs/QA/Automation/index.md
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/VALetters.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#8651 Added "Monthly App Store Review Process Page" to Doc Site
  VAMobile/documentation/docs/UX/Foundations/Information-Architecture.md
  VAMobile/documentation/docs/UX/Foundations/Research/_category_.json
  VAMobile/documentation/docs/UX/Foundations/Research/index.md
  VAMobile/documentation/docs/UX/Foundations/Research/montly-reviews.md
  VAMobile/documentation/docs/UX/Foundations/index.md
Labels: FE-Ready to Merge

#8613 bug/8465-Dylan-RQNotAuthorizedScreensPrioritization
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersListScreen.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.tsx
Labels: FE-Ready to Merge

#8680 Binny 5 21 dev to xl
  .github/ISSUE_TEMPLATE/epic.md
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  VAMobile/.detoxrc.json
  VAMobile/documentation/docs/Engineering/FrontEnd/PushNotifications/DeepLinking.md
  VAMobile/documentation/docs/QA/Automation/AddingNewFeatures.md
  VAMobile/documentation/docs/QA/Automation/index.md
  VAMobile/documentation/docs/QA/Compatibility.md
  VAMobile/documentation/docs/QA/index.md
  VAMobile/documentation/docs/UX/Foundations/Information-Architecture.md
  VAMobile/documentation/docs/UX/Foundations/Research/_category_.json
  VAMobile/documentation/docs/UX/Foundations/Research/index.md
  VAMobile/documentation/docs/UX/Foundations/Research/montly-reviews.md
  VAMobile/documentation/docs/UX/Foundations/index.md
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/VALetters.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/api/queryClient.ts
  VAMobile/src/components/LinkWithAnalytics.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
  VAMobile/src/utils/secureMessaging.tsx
Labels: FE-With QA

#8690 bug/8689-Dylan-EditDraftReplySendMessageFix
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
Labels: FE-Ready to Merge

#8515 feature/8501-Dylan-InPersonVAComponentization
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PendingAppointmentCancelButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCalendarButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCancelReschedule.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentDateAndTime.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentDetailsModality.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentLocation.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentPersonalContactInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentPreferredModality.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentProvider.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentReasonAndComment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/appointments.tsx
Labels: FE-Ready to Merge

#8682 add json api spec BE docs
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/JSONAPI.md
Labels: FE-With QA

#8696 Ran compression over all app store images
  VAMobile/android/fastlane/metadata/android/en-US/images/featureGraphic.png
  VAMobile/android/fastlane/metadata/android/en-US/images/icon.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/4_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/6_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/7_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/8_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/1_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/2_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/3_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/4_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/5_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/6_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/7_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/8_en-US.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-1.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-10.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-2.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-3.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-4.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-5.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-6.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-7.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-8.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-9.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-1.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-10.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-2.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-3.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-4.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-5.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-6.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-7.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-8.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro2ndGen-screen-9.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-1.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-10.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-2.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-3.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-4.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-5.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-6.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-7.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-8.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-9.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-1.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-10.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-2.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-3.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-4.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-5.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-6.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-7.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-8.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-9.png
Labels: FE-Ready to Merge

#8700 Updated the app store image documentation
  VAMobile/documentation/docs/Operations/Updating the App Stores.md
Labels: FE-With QA

#8701 bug/8535-Dylan-WhatsNewDocumentationImprovement
  VAMobile/documentation/docs/App Features/EncouragedUpdate/EncouragedUpdate.md
  VAMobile/documentation/docs/App Features/WhatsNew/WhatsNew.md
Labels: FE-Ready to Merge

#8703 Retire duplicative documentation
  VAMobile/documentation/docs/About our team/index.md
  VAMobile/documentation/docs/About our team/team-charter.md
  VAMobile/documentation/docs/About our team/team-norms.md
  VAMobile/documentation/docs/About our team/who-we-are.md
  VAMobile/documentation/docs/Engineering/FrontEnd/DevSetupProcess.md
Labels: FE-With QA

#8708 bug/8691-Dylan-SendEditDraftRefresh
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.tsx
Labels: FE-Ready to Merge

#8709 bug/7406-Dylan-AFUseCase2UploadPhotoFileBeforeBackNavPopupFix
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.tsx
Labels: FE-Ready to Merge

#8710 Adding documentation to the doc site
  VAMobile/documentation/docs/Flagship design library/Components/Buttons and Links/index.md
  VAMobile/documentation/docs/Operations/Updating the App Stores.md
  VAMobile/documentation/static/img/buttonvslink.png
Labels: FE-With QA

#8694 8130-rachael-detox-add-platform-name-to-default-test-run
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  .github/workflows/update_testrail_results.yml
Labels: FE-Ready to Merge

#8735 bug/8734-rachael-fix-nightly-build-error-android
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-With QA

#8684 bug/7865-theo-IncorrectPhoneNumberAnnounced
  VAMobile/src/components/CommonErrorComponents/CallHelpCenter.tsx
Labels: FE-Ready to Merge

#8718 bug/Binny-7756-ManageAccountCopyChanges
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/ios/Podfile.lock
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeStackScreens.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/AccountSecurity/AccountSecurity.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/AccountSecurity/AccountSecurity.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/ManageYourAccount/ManageYourAccount.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/waygateConfig.ts
Labels: FE-Ready to Merge

#8720 Bug/Binny-8455-RemoveExtraHints
  VAMobile/src/components/CtaButton.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#8679 feature/8582-theo-AnalyticsForRQRetries
  VAMobile/src/api/contactInformation/getContactInformation.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressSummary/AddressSummary.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
Labels: FE-Ready to Merge

#8715 feature/8610-chris-appointments-claim-exam
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/ClaimExamAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/ClaimExamAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCalendarButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCancelReschedule.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentDetailsModality.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentLocation.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentReasonAndComment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#8721 bug/8510-Dylan-DraftMessagesInvalidDateMessageThreads
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#8727 feature/8609/Dylan-VideoGFEAppointments
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCalendarButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCancelReschedule.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentDetailsModality.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentProvider.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoGFEAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoGFEAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#8533 bug/8503-rachael-fix-detox-mapping-logic-errors
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_detox_mapping.yml
  .github/workflows/e2e_ios.yml
Labels: FE-With QA

#8635 bug/8584-theo-RQOptimizations
  VAMobile/src/api/appointments/getAppointments.tsx
  VAMobile/src/api/claimsAndAppeals/getClaimsAndAppeals.tsx
  VAMobile/src/api/prescriptions/getPrescriptions.tsx
  VAMobile/src/api/secureMessaging/getFolderMessages.tsx
  VAMobile/src/api/secureMessaging/saveDraft.tsx
  VAMobile/src/api/vaccines/getVaccines.tsx
  VAMobile/src/constants/common.ts
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppeals/NoClaimsAndAppeals.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppeals/NoClaimsAndAppeals.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointments.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CancelConfirmations/ComposeCancelConfirmation.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Inbox/Inbox.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Inbox/Inbox.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineList/VaccineListScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.test.tsx
  VAMobile/src/store/api/demo/mocks/secureMessaging.json
  VAMobile/src/store/api/demo/mocks/vaccine.json
  VAMobile/src/store/api/demo/secureMessaging.ts
  VAMobile/src/store/api/demo/vaccine.ts
  VAMobile/src/utils/appointments.tsx
Labels: FE-Ready to Merge

#8745 bug/8744-Dylan-ChangeStaleTimeMessageThreads
  VAMobile/src/api/secureMessaging/getThread.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CancelConfirmations/ComposeCancelConfirmation.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.test.tsx
Labels: FE-Ready to Merge

#8755 Updated token pages on doc site
  VAMobile/documentation/design/Foundation/Design tokens/Color.md
  VAMobile/documentation/design/Foundation/Design tokens/Overview.md
Labels: FE-With QA

#8640 Automation/7586-slack-alert-when-approve-command-fails
  .github/workflows/release_pull_request.yml
Labels: FE-Changes Requested, FE-Ready to Merge

#8749 feature/8606-Dylan-VideoAtlas
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCalendarButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCancelReschedule.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentDetailsModality.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentLocation.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentProvider.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoAtlasAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoAtlasAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge
