Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-04, with the labels that each got.

#8270 bug/8044-Dylan-SpecialCharactersSecureMessagingFix
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.tsx
  VAMobile/src/store/api/demo/mocks/secureMessaging.json
  VAMobile/src/utils/jsonFormatting.ts
Labels: FE-With QA

#8275 bug/7907-Dylan-UpdateClaimHelpLinkCopy
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/WhatDoIDoIfDisagreement/WhatDoIDoIfDisagreement.test.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#8273 bug/8191-Dylan-TypeOfCareNotUsingHealthcareServiceFallback
  .github/workflows/build_ios.yml
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/TypeOfCare.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/TypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.test.tsx
  VAMobile/src/utils/appointments.tsx
Labels: FE-With QA

#8274 bug/7919-Dylan-ClaimsSubmittedToReceived
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/AppealsExpanded.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#8269 bug/8075-Dylan-NotificationDemoModeToggleLabels
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/src/store/api/demo/mocks/notifications.json
Labels: FE-With QA

#8268 bug/7461-Dylan-ContradictorySlackMessagesOnE2ETests
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-With QA

#8263 bug/8169-Chika-CrisisLineFontSizeFix
  .github/workflows/build_ios.yml
  VAMobile/src/components/CrisisLineButton.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-With QA

#8276 bug/5892-Dylan-HideDecisionLettersButtonIfNoDecisionLetters
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
Labels: FE-With QA

#8293 bug/8292-Dylan-FixingRQDowntimeAlert
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimLettersScreen/ClaimLettersScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersListScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineList/VaccineListScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.tsx
Labels: FE-With QA

#8299 bug/8294-theo-CrisisLineA11yRole
  VAMobile/src/components/CrisisLineButton.test.tsx
  VAMobile/src/components/CrisisLineButton.tsx
  VAMobile/src/screens/HomeScreen/ContactVAScreen/ContactVAScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
Labels: FE-With QA

#8264 Show loading component when refetching RX history
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/LargeNavButton.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
Labels: FE-With QA

#8284 feature/8126-Chika-UseUpcomingDaysFromApiInAppointmentsHomeScreenModule
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/store/api/types/AppointmentData.ts
  VAMobile/src/store/slices/appointmentsSlice.ts
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#8337 bug/8334-chris-infinite-rendering-loop-in-header
  VAMobile/src/components/Templates/HeaderBanner.tsx
Labels: FE-With QA

#8237 CU/8060-Chika-CopyChangeForYoureLeavingAppAlert
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-With QA

#8277 bug/7555-Dylan-SwappedAskForClaimDecisionAnalytics
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.tsx
Labels: FE-With QA

#8262 documentation/8260-Dylan-WhatsNewEncouragedUpdateDocumentation
  VAMobile/documentation/docs/App Features/EncouragedUpdate/EncouragedUpdate.md
  VAMobile/documentation/docs/App Features/WhatsNew/WhatsNew.md
  VAMobile/documentation/static/img/encouragedUpdate/EncouragedUpdate.png
  VAMobile/documentation/static/img/whatsNew/WhatsNewExpanded.png
  VAMobile/documentation/static/img/whatsNew/WhatsNewNotExpanded.png
Labels: FE-Needs Review

#8347 bug/8342-Dylan-FixSlackThreadsOnDetoxBuilds
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-With QA

#8341 bug/8340-Dylan-FixClaimsAndAppealsMissingAnalytics
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
Labels: FE-With QA

#8348 bug/7202-chris-reply-draft-45-days-fix
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/store/api/demo/mocks/secureMessaging.json
Labels: FE-With QA

#8245 feature/7687-chris-use-link-component-health
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/DisabilityRatings.e2e.ts
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/Payments.e2e.ts
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/e2e/tests/SignIn.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/jest/testSetup.ts
  VAMobile/package.json
  VAMobile/src/components/AttachmentLink.test.tsx
  VAMobile/src/components/AttachmentLink.tsx
  VAMobile/src/components/ClickToCallPhoneNumber.tsx
  VAMobile/src/components/ClickToCallPhoneNumberDeprecated.test.tsx
  VAMobile/src/components/ClickToCallPhoneNumberDeprecated.tsx
  VAMobile/src/components/LinkWithAnalytics.tsx
  VAMobile/src/components/index.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber.tsx
  VAMobile/src/screens/HealthScreen/Appointments/NoAppointments/NoAppointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.test.tsx
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NotEnrolledSM/NotEnrolledSM.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NotEnrolledSM/NotEnrolledSM.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyHelp/ReplyHelp.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.test.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineNumbers/VeteransCrisisLineNumbers.test.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineNumbers/VeteransCrisisLineNumbers.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineScreen.test.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/HowToUpdateDirectDepositScreen/HowToUpdateDirectDepositScreen.test.tsx
  VAMobile/src/utils/location.tsx
  VAMobile/yarn.lock
Labels: FE-With QA

#8312 bug/7028-chris-ios-camera-large-panel-layout
  VAMobile/src/components/PhotoUpload.tsx
  VAMobile/src/utils/claims.tsx
  VAMobile/src/utils/secureMessaging.tsx
Labels: FE-With QA

#8417 bug/8374-duckduckgo-custom-tabs-login-fix
  VAMobile/android/app/src/main/java/gov/va/mobileapp/native_modules/CustomTabsIntentModule.kt
Labels: FE-With QA

#8411 feature/8308-theo-FeatureLandingChildTemplateHeader
  VAMobile/src/components/ActivityButton.tsx
  VAMobile/src/components/Templates/CategoryLanding.tsx
  VAMobile/src/components/Templates/FeatureLandingAndChildTemplate.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-With QA

#8410 bug/8409-Dylan-FixingDetoxE2EScheduledWorkflow
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-With QA

#8456 feature/8452-chris-update-direct-deposit-copy
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#8336 CU/7744-Dylan-ApptsReactQuery2
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/src/api/appointments/cancelAppointment.tsx
  VAMobile/src/api/appointments/getAppointments.tsx
  VAMobile/src/api/appointments/index.ts
  VAMobile/src/api/appointments/queryKeys.ts
  VAMobile/src/api/types/AppointmentData.ts
  VAMobile/src/api/types/PrescriptionData.ts
  VAMobile/src/api/types/index.ts
  VAMobile/src/components/ClickToCallPhoneNumber.test.tsx
  VAMobile/src/components/ClickToCallPhoneNumber.tsx
  VAMobile/src/components/ClickToCallPhoneNumberDeprecated.test.tsx
  VAMobile/src/components/ClickToCallPhoneNumberDeprecated.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAlert.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAlert.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentReason.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentReason.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ClinicNameAndPhysicalLocation.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ContactInformation.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ContactInformation.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PendingAppointmentCancelButton.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PendingAppointmentCancelButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredAppointmentType.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredAppointmentType.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredDateAndTime.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredDateAndTime.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ProviderName.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ProviderName.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/TypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointments.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointments.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/store/api/demo/appointments.ts
  VAMobile/src/store/api/types/index.ts
  VAMobile/src/store/index.ts
  VAMobile/src/store/slices/appointmentsSlice.test.ts
  VAMobile/src/store/slices/appointmentsSlice.ts
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/store/slices/index.ts
  VAMobile/src/testUtils.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/appointments.tsx
  VAMobile/src/utils/tests/appointments.tsx
Labels: FE-With QA

#8402 feature/8038-theo-BenefitsScreenEdgeCases
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/styles/themes/standardTheme.ts
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#8462 Binny-Test-App-Store-Throws
  VAMobile/android/Gemfile.lock
  VAMobile/ios/Gemfile.lock
  VAMobile/src/components/EncourageUpdate.tsx
  VAMobile/src/components/WaygateWrapper.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/utils/homeScreenAlerts.ts
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-With QA

#8252 feature/7291-Dylan-MoreGithubEnhancements
  .github/workflows/label_pull_request_onCreate.yml
  .github/workflows/label_pull_request_onReview.yml
Labels: FE-With QA

#8135 feature/8081-rachael-detox-automatically-run-on-PR
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_detox_mapping.yml
  .github/workflows/e2e_ios.yml
Labels: FE-With QA

#8444 feature/8184-theo-SpaceForceSVG
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/dodIcons.md
  VAMobile/src/api/types/ServiceHistoryData.ts
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
  VAMobile/src/components/VAIcon/svgs/dodBranch/SpaceForce.svg
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
Labels: FE-With QA

#8446 bug/8443-theo-MissingPersonalandContactInfoAnalytics
  VAMobile/src/api/contactInformation/deleteAddress.tsx
  VAMobile/src/api/contactInformation/deleteEmail.tsx
  VAMobile/src/api/contactInformation/deletePhoneNumber.tsx
  VAMobile/src/api/contactInformation/saveAddress.tsx
  VAMobile/src/api/contactInformation/saveEmail.tsx
  VAMobile/src/api/contactInformation/savePhoneNumber.tsx
  VAMobile/src/api/demographics/updateGenderIdentity.tsx
  VAMobile/src/api/demographics/updatePreferredName.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
Labels: FE-Ready to Merge

#8431 bug/8049-theo-VAHeaderAlignment
  VAMobile/src/components/Templates/HeaderBanner.tsx
Labels: FE-Ready to Merge

#8493 Update epic.md
  .github/ISSUE_TEMPLATE/epic.md
Labels: FE-Ready to Merge

#8495 Merge dev into HSP XL 4-29
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_detox_mapping.yml
  .github/workflows/e2e_ios.yml
  .github/workflows/label_pull_request_onCreate.yml
  .github/workflows/label_pull_request_onReview.yml
  VAMobile/documentation/.gitignore
  VAMobile/documentation/design/About/For engineers/assets.md
  VAMobile/documentation/design/About/For engineers/changelog.md
  VAMobile/documentation/design/About/For engineers/components.md
  VAMobile/documentation/design/About/For engineers/contributing.md
  VAMobile/documentation/design/About/For engineers/linting.md
  VAMobile/documentation/design/About/For engineers/overview.md
  VAMobile/documentation/design/About/For engineers/testing.md
  VAMobile/documentation/design/About/For engineers/tokens.md
  VAMobile/documentation/design/About/For engineers/versioning.md
  VAMobile/documentation/design/Components/Alerts and Progress/Alert.md
  VAMobile/documentation/design/Components/Buttons and links/Button.md
  VAMobile/documentation/design/Components/Navigation/Secondary/SegmentedControl.md
  VAMobile/documentation/design/intro.md
  VAMobile/documentation/docs/Flagship design library/Components/Alerts and Progress/AlertBox.mdx
  VAMobile/documentation/docs/UX/Foundations/Accessibility/a11y-checklist-content-designers.md
  VAMobile/documentation/docs/UX/Foundations/Accessibility/a11y-checklist-ux-designers.md
  VAMobile/documentation/docs/UX/Foundations/Accessibility/resources.md
  VAMobile/documentation/docs/UX/How-We-Work/figma-components.md
  VAMobile/documentation/docs/UX/How-We-Work/figma-permissions.md
  VAMobile/documentation/docusaurus.config.js
  VAMobile/src/api/contactInformation/deleteAddress.tsx
  VAMobile/src/api/contactInformation/deleteEmail.tsx
  VAMobile/src/api/contactInformation/deletePhoneNumber.tsx
  VAMobile/src/api/contactInformation/saveAddress.tsx
  VAMobile/src/api/contactInformation/saveEmail.tsx
  VAMobile/src/api/contactInformation/savePhoneNumber.tsx
  VAMobile/src/api/demographics/updateGenderIdentity.tsx
  VAMobile/src/api/demographics/updatePreferredName.tsx
  VAMobile/src/components/Templates/HeaderBanner.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
Labels: FE-With QA

#8451 bug/8442-Dylan-EUAnalyticFix
  VAMobile/src/components/EncourageUpdate.tsx
Labels: FE-Ready to Merge
