Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-08, with the labels that each got.

#9238 BUG - Version Mismatch Between ChromeDriver and Installed Chrome Browser
  .github/workflows/documentation_accessibility_checks.yml
Labels: FE-Changes Requested, FE-Ready to Merge

#9243 bug/9242-rachael-detox-overnight-failures
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/ContactInformation.e2e.ts
  VAMobile/e2e/tests/DecisionLetters.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
Labels: FE-Ready to Merge

#9249 bug/9248-Binny-LetterDownloadInAppReviewBehavior
  VAMobile/src/api/letters/downloadLetter.tsx
Labels: FE-Ready to Merge

#9250 feature/9244-Binny-VamaReviewPrompt
  VAMobile/src/constants/analytics.ts
  VAMobile/src/utils/inAppReviews.tsx
Labels: FE-Ready to Merge

#9262 Update fastlane email to VA
  VAMobile/ios/fastlane/Appfile
Labels: FE-Ready to Merge

#9152 bug/8891-GlobalScreensSpacing
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/HowWillYouScreen/HowWillYouScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/IncorrectServiceInfo/IncorrectServiceInfo.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/WhatToKnowScreen/WhatToKnowScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/HowDoIUpdateScreen/HowDoIUpdateScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineNumbers/VeteransCrisisLineNumbers.tsx
  VAMobile/src/screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineScreen.tsx
  VAMobile/src/screens/auth/LoaGate/LoaGate.tsx
Labels: FE-Ready to Merge

#9259 feature/8452-UpdateDirectDepositCopy
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9254 bug/9225-FixApptListSpacing
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointments.tsx
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.tsx
Labels: FE-Ready to Merge

#9268 Update release_ticket.md
  .github/ISSUE_TEMPLATE/release_ticket.md
Labels: FE-Ready to Merge

#9223 [Docs] Add docs that cover common issues with releases
  VAMobile/documentation/docs/Engineering/DevOps/Automation Code Docs/GitHub Actions/ReleaseIssues.md
Labels: FE-Ready to Merge

#9083 feature/8898-UpdateClaimPhaseComponent
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/src/api/types/ClaimsAndAppealsData.ts
  VAMobile/src/constants/claims.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimTimeline.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimTimeline.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimPhase.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/claimData.ts
  VAMobile/src/store/api/demo/mocks/claims.json
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/claims.tsx
Labels: FE-Ready to Merge

#9251 feature/9221-Binny-UpdateInAppReviewEventLocations
  VAMobile/src/api/contactInformation/deleteEmail.tsx
  VAMobile/src/api/contactInformation/saveAddress.tsx
  VAMobile/src/api/contactInformation/saveEmail.tsx
  VAMobile/src/api/contactInformation/savePhoneNumber.tsx
  VAMobile/src/api/decisionLetters/downloadDecisionLetter.tsx
  VAMobile/src/api/demographics/updateGenderIdentity.tsx
  VAMobile/src/api/demographics/updatePreferredName.tsx
  VAMobile/src/api/directDeposit/updateBankInfo.tsx
  VAMobile/src/api/prescriptions/requestRefills.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentDetailsScreen/PaymentDetailsScreen.tsx
Labels: FE-Ready to Merge

#9290 Bug/9236-Binny-DisRatingSRFix
  VAMobile/e2e/tests/DisabilityRatings.e2e.ts
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
Labels: FE-Ready to Merge

#9303 bug/9054-LinkOverflow
  VAMobile/src/components/LinkWithAnalytics.tsx
Labels: FE-Ready to Merge

#9285 bug/9174-APICallsDuringLogout
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
Labels: FE-Ready to Merge

#9291 bug/8586-AndroidNavBarColor
  VAMobile/src/components/NavigationTabBar.tsx
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-Ready to Merge

#9300 feature/9276-accordion-event-current-step
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimPhase.tsx
Labels: FE-Ready to Merge

#9121 feature/8889-ActiveClaimsAlertAndLinkAndDetailsAndPanel
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimTimeline.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimTimeline.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ConsolidatedClaimsNote/ConsolidatedClaimsNote.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ConsolidatedClaimsNote/ConsolidatedClaimsNote.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9142 feature/8874-ListViewInformationPillsUpdate
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/src/api/types/ClaimsAndAppealsData.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/store/api/demo/mocks/claims.json
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9297 feature/8866-add-step-x-and-moved-to-step-date
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/store/api/demo/mocks/claims.json
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9082 bug/8980-rachael-detox-fix-image-snapshot-failures
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#9313 9160-reorganizing-QA-doc-site
  VAMobile/documentation/docs/Engineering/BackEnd/Features/PushNotifications.md
  VAMobile/documentation/docs/Engineering/FrontEnd/PushNotifications/DeepLinking.md
  VAMobile/documentation/docs/QA/HowWeWork/Meetings.md
  VAMobile/documentation/docs/QA/HowWeWork/index.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/_category_.json
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/a11y-checklist-content-designers.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/a11y-checklist-ux-designers.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/index.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/resources.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/testing-plan.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Automation/AddingNewFeatures.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Automation/Detox Best Practices.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Automation/index.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Compatibility.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Release Testing.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Resources.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Tool Setup.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/index.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/working-with-others.md
  VAMobile/documentation/docs/QA/index.md
  VAMobile/documentation/docs/UX/Foundations/index.md
  VAMobile/documentation/docs/UX/index.md
Labels: FE-Ready to Merge

#9292 bug/7522-AFScreenRerenderOnBack
  VAMobile/src/components/WaygateWrapper.tsx
Labels: FE-Ready to Merge

#9341 Documentation: Update page for designers
  VAMobile/documentation/design/About/designers.md
Labels: FE-With QA

#9305 bug/9266-JSONParseError
  VAMobile/src/store/api/api.test.ts
  VAMobile/src/store/api/api.ts
Labels: FE-Ready to Merge

#9334 bug/9333-Binny-DisableClaimScrollForFileRequests
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.tsx
Labels: FE-Ready to Merge

#9354 bug\9353-Binny-ClaimsMovedToStepFix
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
Labels: FE-Ready to Merge

#9337 bug/9336-Binny-FixDemoModeClaimData
  VAMobile/src/store/api/demo/mocks/claims.json
Labels: FE-Ready to Merge

#9349 bug/9338-Binny-ClosedClaimStepAccuracy
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClosedClaimInfo/ClosedClaimStatusDetails.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.test.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9361 bug/9330-rachael-claims-fix-detox
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/AppealsExpanded.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
Labels: FE-With QA

#9359 feature\9358-Binny-EnableClaimPhaseExpansionByDefault
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/AppealsExpanded.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/DecisionLetters.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge

#9368 Update CustomErrorResponses.md
  VAMobile/documentation/docs/Engineering/BackEnd/Features/CustomErrorResponses.md
Labels: FE-With QA

#8849 8603-Chika-AFStyleAPIErrorHandlingCustomization
  VAMobile/src/components/CommonErrorComponents/CustomError.test.tsx
  VAMobile/src/components/CommonErrorComponents/CustomError.tsx
  VAMobile/src/components/CommonErrorComponents/ErrorComponent.tsx
  VAMobile/src/components/CommonErrorComponents/index.ts
  VAMobile/src/constants/analytics.ts
  VAMobile/src/constants/errors.ts
  VAMobile/src/store/api/types/Errors.ts
  VAMobile/src/utils/errors.ts
Labels: FE-Ready to Merge

#9260 bug/9153-StatutoryOptInTextOverlap
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.tsx
Labels: FE-Ready to Merge

#9383 Revert "Bump the babel group across 1 directory with 3 updates"
  VAMobile/package.json
  VAMobile/yarn.lock
Labels: FE-With QA

#9380 chore/9053-update-app-store-images-and-whatsnew
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/4_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/6_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/7_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/8_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/1_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/2_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/3_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/4_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/5_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/6_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/7_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/8_en-US.png
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-1.png
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-6.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-6.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-6.png
Labels: FE-Ready to Merge

#9342 feature/7158-Binny-InAppReviewFeatureFlagForDetox
  VAMobile/e2e/tests/ContactInformation.e2e.ts
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/e2e/tests/Prescriptions.e2e.ts
  VAMobile/e2e/tests/VALetters.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/utils/inAppReviews.tsx
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge

#9331 9321-Chika-ImplementCopyChangesFromTicket9299
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9391 bug\9385-Binny-AnalyticsForMismatchedContentType
  VAMobile/src/constants/analytics.ts
  VAMobile/src/store/api/api.test.ts
  VAMobile/src/store/api/api.ts
Labels: FE-Ready to Merge

#9310 bug/9189-Chika-InfiniteReattemptsOnProfileScreenForAuthorizedServicesError
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
Labels: FE-Ready to Merge

#9396 feature/9386-add-claim-type-code-to-analytics
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
Labels: FE-Ready to Merge

#9381 bug/9366-rachael-detox-fix-nightly-build
  VAMobile/.detoxrc.json
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/DecisionLetters.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Needs Review

#9055 Automation/6809-chanel-automation-add-image-optimization-into-ci
  .github/workflows/optimize-images.yml
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/4_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/6_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/7_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/8_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/1_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/2_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/3_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/4_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/5_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/6_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/7_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/8_en-US.png
Labels: FE-Changes Requested, FE-Ready to Merge

#9417 Updating Impact Definitions
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/index.md
Labels: FE-Ready to Merge

#9413 bug/9326-9382-rachael-detox-fix-artifacts-issues
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  VAMobile/.detoxrc.json
Labels: FE-With QA

#9379 7159-tkd-detox-faster-without-inapp-review
  VAMobile/e2e/tests/AppealsExpanded.e2e.ts
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/ContactInformation.e2e.ts
  VAMobile/e2e/tests/DecisionLetters.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/src/store/api/demo/mocks/claims.json
Labels: FE-Ready to Merge

#9022 feature/8467-UseDesignSystemAlertComponent
  .github/workflows/e2e_detox_mapping.yml
  VAMobile/documentation/docs/Engineering/FrontEnd/CustomHooks/useAutoScrollToElement.mdx
  VAMobile/package.json
  VAMobile/src/components/AlertBox.test.tsx
  VAMobile/src/components/AlertBox.tsx
  VAMobile/src/components/AlertWithHaptics.test.tsx
  VAMobile/src/components/AlertWithHaptics.tsx
  VAMobile/src/components/CollapsibleAlert.test.tsx
  VAMobile/src/components/CollapsibleAlert.tsx
  VAMobile/src/components/CommonErrorComponents/CallHelpCenter.tsx
  VAMobile/src/components/CommonErrorComponents/CustomError.tsx
  VAMobile/src/components/CommonErrorComponents/DowntimeError.test.tsx
  VAMobile/src/components/CommonErrorComponents/DowntimeError.tsx
  VAMobile/src/components/CommonErrorComponents/ErrorAlert.tsx
  VAMobile/src/components/EncourageUpdate.tsx
  VAMobile/src/components/MessageAlert.test.tsx
  VAMobile/src/components/MessageAlert.tsx
  VAMobile/src/components/WaygateWrapper.tsx
  VAMobile/src/components/WhatsNew.tsx
  VAMobile/src/components/index.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/SelectFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/TakePhotos.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimTimeline.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/EstimatedDecisionDate/EstimatedDecisionDate.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/GenericLetter/GenericLetter.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionsDetailsBanner.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNoPrescriptions.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/Attachments/Attachments.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/IndividualMessageErrorComponent.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/NoVaccineRecords/NoVaccineRecords.test.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/NoVaccineRecords/NoVaccineRecords.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineList/VaccineListScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressValidation/AddressValidation.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/HowToUpdateDirectDepositScreen/HowToUpdateDirectDepositScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/HowToUpdateDirectDepositScreen/HowToUpdateDirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/NoPayments/NoPaymentsScreen.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#9429 bug/9325-ClaimsLoadingOnReviewFileRequests
  VAMobile/src/screens/BenefitsScreen/BenefitsStackScreens.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimPhase.tsx
Labels: FE-Ready to Merge

#9422 bug/9289-MessagesInAppReview
  VAMobile/ios/Podfile.lock
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
Labels: FE-Ready to Merge

#9432 chore/9420-improve-development-best-practices
  VAMobile/documentation/docs/Engineering/FrontEnd/DevelopmentBestPractices.md
Labels: FE-Ready to Merge

#9446 Updated screentype description to remove reference to side-by-side bo…
  VAMobile/documentation/docs/Flagship design library/Templates/ScreenTypes.md
Labels: FE-With QA

#9436 bug/9302-HSPButtonsActiveColor
  VAMobile/src/components/ActivityButton.tsx
  VAMobile/src/components/AnnouncementBanner.tsx
  VAMobile/src/components/CrisisLineButton.tsx
  VAMobile/src/components/LargeNavButton.tsx
  VAMobile/src/components/LinkRow.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
Labels: FE-Ready to Merge

#9449 bug/9366-rachael-detox-fix-vsc
  VAMobile/e2e/tests/VeteranStatusCard.e2e.ts
Labels: FE-Ready to Merge

#9457 bug/9288-KeyboardNavigationFixes
  VAMobile/package.json
  VAMobile/patches/@department-of-veterans-affairs+mobile-component-library+0.21.0.patch
  VAMobile/src/components/BaseListItem.tsx
  VAMobile/src/components/DefaultList.test.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/PickerList.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.test.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/components/FormWrapper/FormFields/RadioGroup.test.tsx
  VAMobile/src/components/FormWrapper/FormFields/RadioGroup.tsx
  VAMobile/src/components/FormWrapper/FormFields/VASelector.tsx
  VAMobile/src/components/List.test.tsx
  VAMobile/src/components/MessageList.test.tsx
  VAMobile/src/components/NavigationTabBar.test.tsx
  VAMobile/src/components/NavigationTabBar.tsx
  VAMobile/src/components/RadioGroupModal.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.test.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersListScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersOverviewScreen.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Folders/Folders.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressSummary/AddressSummary.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.test.tsx
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#9475 Doc site - home template update
  VAMobile/documentation/docs/Flagship design library/Templates/ScreenTypes.md
Labels: FE-With QA

#9490 [Docs] Move Design System Changelog
  VAMobile/documentation/docusaurus.config.js
Labels: FE-Ready to Merge

#9494 replaced accidentally omitted content sections
  VAMobile/documentation/docs/Flagship design library/Templates/ScreenTypes.md
Labels: FE-Ready to Merge

#9514 chore/9418-app-store-images-whatsnew-2.36
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/2_en-US.png
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
  VAMobile/ios/fastlane/screenshots/en-US/ipadPro129-screen-2.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone55-screen-2.png
  VAMobile/ios/fastlane/screenshots/en-US/iphone67-screen-2.png
Labels: FE-Ready to Merge

#9500 [Docs] Fix sidebar title for DS changelog
  VAMobile/documentation/docusaurus.config.js
Labels: FE-With QA

#9507 bug/9506-Binny-BlankAboutYouBoxFix
  VAMobile/src/components/Nametag/Nametag.tsx
Labels: FE-Ready to Merge
