Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-10, with the labels that each got.

#9722 feature/9721-ChevronUpDownMigration
  VAMobile/src/components/AccordionCollapsible.tsx
  VAMobile/src/components/CollapsibleView.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
  VAMobile/src/components/VAIcon/svgs/ChevronDown.svg
  VAMobile/src/components/VAIcon/svgs/ChevronUp.svg
Labels: FE-Ready to Merge

#9701 CU/9700-rachael-detox-contact-info-replace-by-text
  VAMobile/e2e/tests/ContactInformation.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
Labels: FE-Ready to Merge

#9654 CU/9652 detox rachael appeals replace by text
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/AppealsExpanded.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData.tsx
Labels: FE-With QA

#9677 CU/9675-rachael-detox-cerner-swap-out-by-text
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/Cerner.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM.tsx
Labels: FE-With QA

#9633 feature/8784-UpdateLogos
  .gitignore
  VAMobile/android/app/src/main/res/drawable-hdpi/va_on_dark.png
  VAMobile/android/app/src/main/res/drawable-hdpi/va_on_light.png
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/dodIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/logoIcons.md
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/MilitaryInformation.e2e.ts
  VAMobile/e2e/tests/VeteranStatusCard.e2e.ts
  VAMobile/ios/VAMobile.xcodeproj/project.pbxproj
  VAMobile/ios/VAMobile/Images.xcassets/va_on_dark.imageset/Contents.json
  VAMobile/ios/VAMobile/Images.xcassets/va_on_dark.imageset/va_on_dark.png
  VAMobile/ios/VAMobile/Images.xcassets/va_on_light.imageset/Contents.json
  VAMobile/ios/VAMobile/Images.xcassets/va_on_light.imageset/va_on_light.png
  VAMobile/package.json
  VAMobile/react-native.config.js
  VAMobile/src/api/types/ServiceHistoryData.ts
  VAMobile/src/components/MilitaryBranchEmblem.tsx
  VAMobile/src/components/Nametag/Nametag.test.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
  VAMobile/src/components/VAIcon/svgs/dodBranch/AirForce.svg
  VAMobile/src/components/VAIcon/svgs/dodBranch/Army.svg
  VAMobile/src/components/VAIcon/svgs/dodBranch/CoastGuard.svg
  VAMobile/src/components/VAIcon/svgs/dodBranch/MarineCorps.svg
  VAMobile/src/components/VAIcon/svgs/dodBranch/Navy.svg
  VAMobile/src/components/VAIcon/svgs/dodBranch/SpaceForce.svg
  VAMobile/src/components/VAIcon/svgs/vaParentLogo/Logo.svg
  VAMobile/src/components/VALogo/VALogo.tsx
  VAMobile/src/components/index.ts
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/screens/OnboardingCarousel/GenericOnboarding/GenericOnboarding.tsx
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#9698 CU/9697-rachael-detox-claims-replace-by-text
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequestDetails/FileRequestDetails.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ConsolidatedClaimsNote/ConsolidatedClaimsNote.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/WhatDoIDoIfDisagreement/WhatDoIDoIfDisagreement.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
Labels: FE-Ready to Merge

#9624 bug/9623-rachael-detox-fix-nightly-ticket-creation-logic
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-With QA

#9707 CU/9706-rachael-detox-direct-deposit-replace-by-text
  VAMobile/e2e/tests/DirectDeposit.e2e.ts
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.tsx
Labels: FE-Ready to Merge

#9761 CU/9760-chanel-update-qa-reviewer-list-for-pr-check
  .github/workflows/qa_required_approvals.yml
Labels: FE-Ready to Merge

#9702 chore/5743-Setupi18nInUnitTests
  VAMobile/documentation/docs/Engineering/FrontEnd/Testing/UnitTesting.md
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.test.tsx
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/TermsAndConditions/TermsAndConditions.test.tsx
Labels: FE-Ready to Merge

#9754 cu: Update Documentation to remove non existent imports
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/commonIcons.md
Labels: FE-With QA

#9757 bug/9756-rachael-detox-fix-auto-run-per-PR
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-Ready to Merge

#8254 CU/8253-Dylan-NotificationRQMigration
  VAMobile/patches/react-native-notifications+5.1.0.patch
  VAMobile/src/App.tsx
  VAMobile/src/api/notifications/getPushPreferences.tsx
  VAMobile/src/api/notifications/getSystemNotificationSettings.tsx
  VAMobile/src/api/notifications/index.ts
  VAMobile/src/api/notifications/queryKeys.ts
  VAMobile/src/api/notifications/registerDevice.tsx
  VAMobile/src/api/notifications/updatePushPreferences.tsx
  VAMobile/src/api/types/Notifications.ts
  VAMobile/src/api/types/index.ts
  VAMobile/src/components/NotificationManager/NotificationManager.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.tsx
  VAMobile/src/store/api/demo/notifications.ts
  VAMobile/src/store/api/types/index.ts
  VAMobile/src/store/index.ts
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/store/slices/index.ts
  VAMobile/src/store/slices/notificationSlice.ts
  VAMobile/src/testUtils.tsx
Labels: FE-Ready to Merge

#9747 bug/9746-rachael-detox-fix-nightly-build-errors
  .github/workflows/e2e_ios.yml
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/e2e/tests/LoginScreen.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/PushNotifications.e2e.ts
  VAMobile/e2e/tests/SignIn.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#9736 cu: 5779 Audit VABulletList for a11yLabel usage
  VAMobile/src/components/VABulletList.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClosedClaimInfo/ClosedClaimStatusDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionsDetailsBanner.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyHelp/ReplyHelp.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/WhatToKnowScreen/WhatToKnowScreen.tsx
  VAMobile/src/screens/auth/LoaGate/LoaGate.tsx
Labels: FE-Ready to Merge

#9793 CU/9792-rachael-detox-payments-replace-by-text
  VAMobile/e2e/tests/Payments.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentDetailsScreen/PaymentDetailsScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentIssueScreen/PaymentIssueScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentMissingSceen/PaymentMissingScreen.tsx
Labels: FE-With QA

#9789 CU/9788-rachael-detox-onboarding-replace-by-text
  VAMobile/e2e/tests/Onboarding.e2e.ts
Labels: FE-Ready to Merge

#9810 Publish Checkbox documentation
  VAMobile/documentation/design/Components/Selection and input/Checkbox.md
  VAMobile/documentation/design/intro.md
  VAMobile/documentation/docs/Flagship design library/Components/Selection and Input/Form Elements/Checkbox.md
  VAMobile/documentation/docs/UX/How-We-Work/figma-permissions.md
Labels: FE-With QA

#9799 CU/9798-rachael-detox-personal-info-replace-by-text
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/WhatToKnowScreen/WhatToKnowScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/HowDoIUpdateScreen/HowDoIUpdateScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PreferredNameScreen/PreferredNameScreen.tsx
Labels: FE-Ready to Merge

#9826 QA rotation automation and ticket template updates
  .github/ISSUE_TEMPLATE/External Bug Submission Template.md
  .github/ISSUE_TEMPLATE/Post_RC_Code_Change.md
  .github/ISSUE_TEMPLATE/detox_nightly_build_failure.md
  .github/ISSUE_TEMPLATE/release_ticket.md
  .github/workflows/release_branch_issue.yml
Labels: FE-Ready to Merge

#9812 CU/9811-rachael-detox-settings-replace-by-text
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/AccountSecurity/AccountSecurity.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.tsx
Labels: FE-Ready to Merge

#9814 CU/9813-rachael-detox-vaccines-replace-by-text
  VAMobile/e2e/tests/VaccineRecords.e2e.ts
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineDetails/VaccineDetailsScreen.tsx
Labels: FE-Ready to Merge

#9823 CU/9822-rachael-detox-VALetters-replace-by-text
  VAMobile/e2e/tests/VALetters.e2e.ts
  VAMobile/src/screens/BenefitsScreen/Letters/BenefitSummaryServiceVerification/BenefitSummaryServiceVerification.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/GenericLetter/GenericLetter.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersOverviewScreen.tsx
Labels: FE-Ready to Merge

#9412 feature/9286-SingleSignOn
  VAMobile/android/app/src/main/java/gov/va/mobileapp/native_modules/CustomTabsIntentModule.kt
  VAMobile/documentation/docs/Engineering/FrontEnd/SingleSignOn.md
  VAMobile/env/constant.env
  VAMobile/env/env.sh
  VAMobile/ios/Podfile.lock
  VAMobile/ios/RNAuthSession.swift
  VAMobile/ios/VAMobile.xcodeproj/project.pbxproj
  VAMobile/jest/testSetup.ts
  VAMobile/package.json
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/Appointments/NoAppointments/NoAppointments.tsx
  VAMobile/src/screens/WebviewScreen/WebviewScreen.tsx
  VAMobile/src/store/api/types/auth.ts
  VAMobile/src/store/slices/authSlice.sis.test.ts
  VAMobile/src/store/slices/authSlice.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/auth.ts
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#9787 CU/9786-rachael-detox-messages-replace-by-text
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/CrisisLineButton.tsx
  VAMobile/src/components/FormWrapper/FormFields/FormAttachments.tsx
  VAMobile/src/components/Templates/FeatureLandingAndChildTemplate.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/Attachments/Attachments.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
Labels: FE-Ready to Merge

#9857 IA page link update
  VAMobile/documentation/docs/UX/Foundations/Information-Architecture.md
Labels: FE-Ready to Merge

#9868 Automation/9847-remove-label-pull-request-oncreateyml-workflow
  .github/workflows/label_pull_request_onCreate.yml
Labels: FE-Ready to Merge

#9820 Automation/5721-chanel-add-flag-to-bypass-realease-check-date-release-branch
  .github/workflows/new_release_branch.yml
  VAMobile/release_branch.sh
Labels: FE-Ready to Merge

#9729 bug/9253-Chika-ScreenViewTypeInstantlyRequestReview
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentDetailsScreen/PaymentDetailsScreen.tsx
  VAMobile/src/utils/inAppReviews.tsx
Labels: FE-Ready to Merge

#9825 CU/9824-rachael-detox-veteransCrisisLine-replace-by-text
  VAMobile/e2e/tests/VeteransCrisisLine.e2e.ts
Labels: FE-Ready to Merge

#9802 CU: Remove hideArrow code from AccordionCollapsible
  VAMobile/src/components/AccordionCollapsible.test.tsx
  VAMobile/src/components/AccordionCollapsible.tsx
Labels: FE-Ready to Merge

#9898 bug/9897-rachael-detox-fix-nightly-build-error-ticket-creation-logic
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-Ready to Merge

#9821 feature/6975-Chika-AddAnalyticForWebviewFailEvent
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/WebviewScreen/WebviewScreen.tsx
Labels: FE-Ready to Merge

#9908 Add info about holiday release freeze
  VAMobile/documentation/docs/intro.md
Labels: FE-With QA

#9784 bug/7837-updateRxAppHeadings
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionCommon/PrescriptionListItem.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionCommon/PrescriptionListItem.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/DetailsTextSections.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHelp/PrescriptionHelp.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/StatusDefinition/StatusDefinition.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/StatusDefinition/StatusDefinition.tsx
Labels: FE-Ready to Merge

#9912 Add release calendar to docs site
  VAMobile/documentation/docs/Operations/Releases/index.md
Labels: FE-With QA

#9907 home screen description & guidelines
  VAMobile/documentation/docs/Flagship design library/Templates/Home.md
  VAMobile/documentation/docs/Flagship design library/Templates/ScreenTypes.md
  VAMobile/documentation/docs/Flagship design library/Templates/image.png
  VAMobile/documentation/static/img/home/vamobile-home-zones.png
Labels: FE-Ready to Merge

#9914 9818 document openapi testing
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/Endpoint Creation Checklist.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/ErrorHandling.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/ModelsAndSerializers.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/OpenAPIDocumentation.md
Labels: FE-With QA

#9917 Home---doc-site-corrections
  VAMobile/documentation/docs/Flagship design library/Templates/Home.md
  VAMobile/documentation/docs/Flagship design library/Templates/ScreenTypes.md
Labels: FE-Changes Requested, FE-Ready to Merge

#9867 bug/9735-chanel-pr-label-automation-should-remove-other-labels-when-ready-to-merge
  .github/workflows/label_pull_request_onReview.yml
Labels: QA, devops, QA and Release, FE-Ready to Merge

#9928 Add contributing docs
  VAMobile/documentation/docs/About our team/_category_.json
  VAMobile/documentation/docs/App Features/_category_.json
  VAMobile/documentation/docs/Engineering/_category_.json
  VAMobile/documentation/docs/Flagship design library/_category_.json
  VAMobile/documentation/docs/Operations/_category_.json
  VAMobile/documentation/docs/Product/_category_.json
  VAMobile/documentation/docs/QA/_category_.json
  VAMobile/documentation/docs/UX/_category_.json
  VAMobile/documentation/docs/contributing.md
Labels: FE-With QA

#9859 feature/9759-Add AppointmentMedicationWording to InPerson Phone & CC
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/env/constant.env
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/CommunityCareAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/CommunityCareAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/PhoneAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/PhoneAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentMedicationWording.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoVAAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoVAAppointment.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/env.ts
Labels: FE-Ready to Merge

#9723 cu: Update fornts webviewTitle and textWithIconButton to min 16
  VAMobile/src/screens/WebviewScreen/WebviewTitle.tsx
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-Ready to Merge

#9974 bug/9964-chanel-ios-2-39-ci-failure
  VAMobile/ios/fastlane/Fastfile
Labels: FE-Ready to Merge

#9931 CU/9878 rachael detox update rc script automation
  .github/workflows/start_test_rail_run.yml
Labels: FE-Ready to Merge

#9983 bug/9982-rachael-detox-fix-logic-start-test-rail-run
  .github/workflows/start_test_rail_run.yml
Labels: FE-Ready to Merge

#9976 Remove iam from docs
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/Auth Diagrams.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/sis.md
  VAMobile/documentation/docs/Engineering/BackEnd/Testing/ApiTokens.md
  VAMobile/documentation/docs/Engineering/BackEnd/Testing/StagingInstances.md
  VAMobile/documentation/static/img/backend/biometrics-flow-for-username-and-password-initial-login.png
  VAMobile/documentation/static/img/backend/biometrics-flow-for-username-and-password-subsequent-login.png
  VAMobile/documentation/static/img/backend/health-and-benefits-biometrics-initial-login.png
  VAMobile/documentation/static/img/backend/health-and-benefits-biometrics-subsequent-login.png
  VAMobile/documentation/static/img/backend/iam-authentication-sequence-diagram.png
  VAMobile/documentation/static/img/backend/username-and-password-authorization-flow.png
  VAMobile/documentation/static/img/backend/vets-api-authentication-activity-diagram.png
Labels: FE-Ready to Merge

#9913 bug/9827-rachael-detox-update-mapping
  .github/workflows/e2e_detox_mapping.yml
Labels: FE-Ready to Merge

#9785 CU: Audit common.json and remove unused strings
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9956 Add accessing demo mode documentation
  VAMobile/documentation/docs/Engineering/FrontEnd/AccessibilityInformation.md
  VAMobile/documentation/docs/Engineering/FrontEnd/CustomHooks/_category_.json
  VAMobile/documentation/docs/Engineering/FrontEnd/DebuggingToolsInstructions.md
  VAMobile/documentation/docs/Engineering/FrontEnd/DemoMode/_category_.json
  VAMobile/documentation/docs/Engineering/FrontEnd/DemoMode/index.md
  VAMobile/documentation/docs/Engineering/FrontEnd/DevSetupProcess.md
  VAMobile/documentation/docs/Engineering/FrontEnd/DowntimeMessages.md
  VAMobile/documentation/docs/Engineering/FrontEnd/PushNotifications/_category_.json
  VAMobile/documentation/docs/Engineering/FrontEnd/ReduxToolkit/Overview/_category_.json
  VAMobile/documentation/docs/Engineering/FrontEnd/ReduxToolkit/Tutorials/_category_.json
  VAMobile/documentation/docs/Engineering/FrontEnd/ReduxToolkit/_category_.json
Labels: FE-With QA

#9986 CU/9985-Remove-Analytic
  VAMobile/src/constants/analytics.ts
  VAMobile/src/store/api/api.ts
Labels: FE-Ready to Merge

#9977 Updating the UX Designer Checklist to include MCAG and Spacing Tokens
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Accessibility/a11y-checklist-ux-designers.md
Labels: FE-Ready to Merge

#9734 feature/9733-VAIconWithTextMigration
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/commonIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/navIcons.md
  VAMobile/src/components/IconWithText/IconWithText.test.tsx
  VAMobile/src/components/IconWithText/IconWithText.tsx
  VAMobile/src/components/IconWithText/index.ts
  VAMobile/src/components/Menu/MenuView.tsx
  VAMobile/src/components/NavigationTabBar.tsx
  VAMobile/src/components/Templates/CategoryLanding.test.tsx
  VAMobile/src/components/Templates/FeatureLandingAndChildTemplate.test.tsx
  VAMobile/src/components/Templates/FullScreenSubtask.test.tsx
  VAMobile/src/components/Templates/FullScreenSubtask.tsx
  VAMobile/src/components/Templates/HeaderBanner.test.tsx
  VAMobile/src/components/Templates/HeaderBanner.tsx
  VAMobile/src/components/VAIcon/VAIcon.test.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
  VAMobile/src/components/VAIcon/svgs/Ellipsis.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/BenefitsSelected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/BenefitsUnselected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/HealthSelected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/HealthUnselected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/HomeSelected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/HomeUnselected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/PaymentsSelected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/PaymentsUnselected.svg
  VAMobile/src/components/VAIcon/svgs/navIcon/ProfileSelected.svg
  VAMobile/src/components/VAIconWithText/VAIconWithText.tsx
  VAMobile/src/components/VAIconWithText/index.ts
  VAMobile/src/components/index.ts
  VAMobile/src/components/types/HeaderButton.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-Ready to Merge

#10006 bug/9965-chanel-chromedriver-version-compability
  .github/workflows/documentation_accessibility_checks.yml
Labels: FE-Ready to Merge

#10024 A11y fix - covert iframe alt to title
  VAMobile/documentation/design/Components/Alerts and progress/Alert.md
  VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
  VAMobile/documentation/design/Components/Buttons and links/Button.md
  VAMobile/documentation/design/Components/Buttons and links/Link.md
  VAMobile/documentation/design/Components/Navigation/Secondary/SegmentedControl.md
  VAMobile/documentation/design/Components/Selection and input/Checkbox.md
  VAMobile/documentation/design/Foundation/Design tokens/Color.md
  VAMobile/documentation/design/Foundation/Design tokens/Spacing.md
  VAMobile/documentation/design/Foundation/Icons.md
Labels: FE-With QA

#10037 bug/revert-9979-chanel-update-fatlane-version-on-ios-and-android
  VAMobile/android/Gemfile.lock
  VAMobile/ios/Gemfile.lock
Labels: FE-Ready to Merge

#9780 feature/9779-MoreIconMigrations
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/commonIcons.md
  VAMobile/src/components/CategoryLandingAlert.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/components/VABulletList.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
  VAMobile/src/components/VAIcon/svgs/Bullet.svg
  VAMobile/src/components/VAIcon/svgs/ExclamationCircle.svg
  VAMobile/src/components/VAIcon/svgs/Sort.svg
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/utils/claims.tsx
Labels: FE-Ready to Merge

#9888 Feature/9763 update medication wording for va video
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentJoinSessionPrepareForVideo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentMedicationWording.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoAtlasAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoAtlasAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoGFEAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoGFEAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoHomeAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoHomeAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/PrepareForVideoVisit/PrepareForVideoVisit.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/PrepareForVideoVisit/PrepareForVideoVisit.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10022 bug/9962-rachael-detox-iOS-android-send-to-testRail-broken
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  .github/workflows/update_testrail_results.yml
Labels: FE-Ready to Merge

#10038 CU/9768-Chika-Rollback-2779-and-test-RQ
  VAMobile/src/api/claimsAndAppeals/getAppeal.tsx
  VAMobile/src/api/claimsAndAppeals/getClaim.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.tsx
  VAMobile/src/store/api/api.ts
Labels: FE-Ready to Merge

#10025 A11y fix - add or correct accessibility of iframes for various documentation parts
  VAMobile/documentation/docs/Flagship design library/Components/Buttons and Links/Menus.md
  VAMobile/documentation/docs/Flagship design library/Components/Layout and Organization/List/ListHeader.md
  VAMobile/documentation/docs/Flagship design library/Components/Layout and Organization/MultiTouchCard.mdx
  VAMobile/documentation/docs/Flagship design library/Components/Layout and Organization/Nametag.md
  VAMobile/documentation/docs/Flagship design library/Components/Navigation/Secondary/Pagination.mdx
  VAMobile/documentation/docs/Flagship design library/Components/Selection and Input/Form Elements/RadioButton.md
  VAMobile/documentation/docs/Flagship design library/Components/Selection and Input/Form Elements/VATextInput.mdx
  VAMobile/documentation/docs/Flagship design library/Components/Tags/Tag.mdx
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/index.md
  VAMobile/documentation/docs/Flagship design library/Foundation/color-palette.md
  VAMobile/documentation/docs/Flagship design library/Foundation/layout.md
  VAMobile/documentation/docs/Flagship design library/Foundation/typography.md
  VAMobile/documentation/docs/Flagship design library/Templates/NavigationModel.md
  VAMobile/documentation/docs/Flagship design library/Templates/ScreenTypes.md
  VAMobile/documentation/docs/Operations/App metrics/Dashboard.md
  VAMobile/documentation/docs/Operations/Releases/release-process.md
  VAMobile/documentation/docs/UX/Foundations/Information-Architecture.md
Labels: FE-With QA

#10026 Fixing a11y issues for the app features section of the docs site
  VAMobile/documentation/docs/App Features/Availability Framework/Availability Framework.md
  VAMobile/documentation/docs/App Features/EncouragedUpdate/EncouragedUpdate.md
  VAMobile/documentation/docs/App Features/WhatsNew/WhatsNew.md
Labels: FE-With QA

#10039 9205 updating years in demo mode
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/Payments.e2e.ts
  VAMobile/src/store/api/demo/mocks/payments.json
  VAMobile/src/store/api/demo/mocks/secureMessaging.json
  VAMobile/src/store/api/demo/payments.ts
Labels: FE-Ready to Merge
