Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-12, with the labels that each got.

#10260 CU/9955-rachael-detox-add-comments-to-utils
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#10284 action sheet/snackbar copy updates in claims.json
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10237 feature/Binny-10233-CreatePIIFilter
  VAMobile/src/constants/common.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppFeedbackScreen/InAppFeedbackScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/common.ts
Labels: FE-Ready to Merge

#10248 bug/9636-Binny-FixPaginationAnnounce
  VAMobile/src/components/Pagination.test.tsx
  VAMobile/src/components/Pagination.tsx
Labels: FE-Ready to Merge

#10235 Adding Component Documentation Guide
  VAMobile/documentation/docs/Flagship design library/Components/documentation-guide.md
Labels: FE-Ready to Merge

#10290 bug/10289-rachael-detox-fix-overnight-failures
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#9919 spike/9918-rachael-detox-add-what-to-run-to-code
  .github/workflows/e2e_detox_mapping.yml
  VAMobile/e2e/detoxMapping.json
Labels: FE-Ready to Merge

#10287 bug/10285-rachael-detox-fix-workflow-failing-after-retry-passes
  .github/workflows/e2e_android.yml
Labels: FE-Ready to Merge

#10266 feature/9661-Chika-AddDODToProofOfVeteranStatus
  VAMobile/e2e/tests/VeteranStatusCard.e2e.ts
  VAMobile/src/api/types/PersonalInformationData.ts
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/store/api/demo/mocks/personalInformation.json
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10300 Update feature-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: FE-With QA

#10302 bug/10301-rachael-detox-fix-error-in-e2e-mapping
  .github/workflows/e2e_detox_mapping.yml
  VAMobile/e2e/detoxMapping.json
Labels: FE-Ready to Merge

#10263 bug/10058-rachael-detox-messages-AF-failing
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
Labels: FE-Ready to Merge

#10306 CU/9944-rachael-detox-add-comments-to-onboarding
  VAMobile/e2e/tests/Onboarding.e2e.ts
Labels: FE-Ready to Merge

#10307 CU/9945-rachael-detox-add-comments-to-payments
  VAMobile/e2e/tests/Payments.e2e.ts
Labels: FE-Ready to Merge

#10309 CU/9948-rachael-detox-add-comments-to-profile
  VAMobile/e2e/tests/ProfileScreen.e2e.ts
Labels: FE-Ready to Merge

#10310 CU/9950-rachael-detox-add-comments-to-settings
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
Labels: FE-Ready to Merge

#10308 CU/9946-rachael-detox-add-comments-to-personalInformationScreen
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
Labels: FE-Ready to Merge

#10249 chore: updated PaymentHistory screens with i18n
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/NoPayments/NoPaymentsScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentIssueScreen/PaymentIssueScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentMissingSceen/PaymentMissingScreen.test.tsx
Labels: FE-Ready to Merge

#10250 chore: Updated ContactInformationScreen tests with i18n
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/HowWillYouScreen/HowWillYouScreen.test.tsx
Labels: FE-Ready to Merge

#10288 chore: Updated Login tests with i18n.
  VAMobile/src/screens/OnboardingCarousel/OnboardingCarousel.test.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.test.tsx
  VAMobile/src/screens/auth/LoaGate/LoaGate.test.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.test.tsx
Labels: FE-Ready to Merge

#10197 CU/10195-rachael-detox-update-android-version
  .github/workflows/e2e_android.yml
  VAMobile/.detoxrc.json
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/HomeScreen.e2e.ts
Labels: FE-Ready to Merge

#10346 Add typography documentation to doc site
  VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
  VAMobile/documentation/design/Components/Selection and input/Checkbox.md
  VAMobile/documentation/design/Components/Typography/Text.md
  VAMobile/documentation/design/Foundation/Design tokens/Typography.md
  VAMobile/documentation/design/intro.md
Labels: FE-With QA

#10350 Add radio button documentation to doc site
  VAMobile/documentation/design/Components/Selection and input/RadioButton.md
  VAMobile/documentation/design/intro.md
  VAMobile/documentation/docs/Flagship design library/Components/Selection and Input/Form Elements/RadioButton.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/_category_.json
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/_iconPathSection.mdx
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/checkboxIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/commonIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/index.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/linksIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/radioBtnIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/Icons/webviewIcons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/color-palette.md
  VAMobile/documentation/docs/Flagship design library/Foundation/color.md
  VAMobile/documentation/docs/Flagship design library/Foundation/icons.md
  VAMobile/documentation/docs/Flagship design library/Foundation/layout.md
  VAMobile/documentation/docs/Flagship design library/Foundation/spacing.md
  VAMobile/documentation/docs/Flagship design library/Foundation/typography.md
Labels: FE-Ready to Merge

#10358 bug/10357-rachael-detox-add-ruby-install-to-e2e-android
  .github/workflows/e2e_android.yml
Labels: FE-Ready to Merge

#10370 doc/fix broken link in QA section
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/index.md
Labels: FE-Ready to Merge

#10352 chore: use i18n in unit tests - Home 5
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/AccountSecurity/AccountSecurity.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.test.tsx
Labels: FE-With QA

#10356 CU/9949-rachael-detox-add-comments-to-push-notifications
  VAMobile/e2e/tests/PushNotifications.e2e.ts
Labels: FE-Ready to Merge

#10362 chore/5057-streamlineUseIsScreenReaderEnabledHook
  VAMobile/documentation/docs/Engineering/FrontEnd/CustomHooks/useIsScreenReaderEnabled.mdx
  VAMobile/src/App.tsx
  VAMobile/src/components/Templates/CategoryLanding.tsx
  VAMobile/src/components/Templates/FeatureLandingAndChildTemplate.tsx
  VAMobile/src/components/Templates/HeaderBanner.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-Ready to Merge

#10359 CU/9850 Detox ApptsExpanded ID cleanup
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
Labels: FE-Ready to Merge

#10380 Changes to content style guide
  VAMobile/documentation/docs/Flagship design library/Content/content-style-guide.md
Labels: FE-Ready to Merge

#10315 10313-MoreIconConversionsAgain
  VAMobile/src/components/AttachmentLink.tsx
  VAMobile/src/components/FormWrapper/FormFields/FormAttachments.tsx
  VAMobile/src/components/LabelTag.tsx
  VAMobile/src/components/LargeNavButton.tsx
  VAMobile/src/components/PhotoPreview.tsx
  VAMobile/src/components/TextLineWithIcon.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/styles/themes/standardTheme.ts
Labels: FE-Ready to Merge

#10381 Updating value prop on landing screen of doc site
  VAMobile/documentation/src/components/HomepageFeatures.tsx
Labels: FE-Ready to Merge

#10382 origin/9312-rachael-add-delete-detoxrc-to-doc-site
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Automation/index.md
Labels: FE-Ready to Merge

#10375 Fixing broken links in UX pages
  VAMobile/documentation/docs/UX/Foundations/Information-Architecture.md
  VAMobile/documentation/docs/UX/Foundations/Research/index.md
  VAMobile/documentation/docs/UX/How-We-Work/designing-ui.md
  VAMobile/documentation/docs/UX/Resources.md
Labels: FE-Ready to Merge

#10279 Feature/10030+10028 create analytics and trigger
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/App.tsx
  VAMobile/src/api/appointments/cancelAppointment.tsx
  VAMobile/src/api/claimsAndAppeals/downloadEFolderDocument.tsx
  VAMobile/src/api/contactInformation/deleteEmail.tsx
  VAMobile/src/api/contactInformation/saveAddress.tsx
  VAMobile/src/api/contactInformation/saveEmail.tsx
  VAMobile/src/api/contactInformation/savePhoneNumber.tsx
  VAMobile/src/api/decisionLetters/downloadDecisionLetter.tsx
  VAMobile/src/api/demographics/updateGenderIdentity.tsx
  VAMobile/src/api/demographics/updatePreferredName.tsx
  VAMobile/src/api/directDeposit/updateBankInfo.tsx
  VAMobile/src/api/letters/downloadLetter.tsx
  VAMobile/src/api/prescriptions/requestRefills.tsx
  VAMobile/src/api/secureMessaging/saveDraft.tsx
  VAMobile/src/api/secureMessaging/sendMessage.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetails.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/ViewMessageScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppFeedbackScreen/InAppFeedbackScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentDetailsScreen/PaymentDetailsScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/hooks/index.tsx
  VAMobile/src/utils/inAppReviews.tsx
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge

#10353 chore: use i18n in unit tests - Home 6
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressSummary/AddressSummary.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/AddressValidation/AddressValidation.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.test.tsx
Labels: FE-Ready to Merge

#10314 CU/10187-Chika-AddBackAnnouncementForScreenreaderUsers
  VAMobile/src/components/Templates/FeatureLandingAndChildTemplate.tsx
  VAMobile/src/components/Templates/HeaderBanner.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10328 Automation/10321-chanel-release-issue-assign-flagship-mobile-approver-members
  .github/ISSUE_TEMPLATE/release_ticket.md
Labels: devops, QA and Release, FE-Ready to Merge

#10168 Automation/9887-spike-chanel-improve-monitoring-when-release-does-not-release
  VAMobile/android/fastlane/Fastfile
  VAMobile/ios/fastlane/Fastfile
Labels: devops, QA and Release, FE-Ready to Merge

#10390 added intro to app store review page
  VAMobile/documentation/docs/UX/Foundations/Research/montly-reviews.md
Labels: FE-Ready to Merge
