Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-06, with the labels that each got.

#8738 CU/8737-rachael-detox-e2e-tests-refactor
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-With QA

#8765 added platform to workflow ownership
  .github/CODEOWNERS
Labels: FE-Ready to Merge

#8754 bug/7762-theo-PreferredNameSnackbar
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PreferredNameScreen/PreferredNameScreen.tsx
Labels: FE-Changes Requested, FE-Ready to Merge

#8774 bug/8769-rachael-detox-nightly-build-error
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
Labels: FE-Ready to Merge

#8758 bug/8739-rachael-detox-stop-overriding-junit-file
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
  VAMobile/.detoxrc.json
Labels: FE-Ready to Merge

#8782 feature/8766-theo-DependabotVulnerabilities
  VAMobile/documentation/package.json
  VAMobile/documentation/yarn.lock
Labels: FE-With QA

#8783 bug/7700-theo-RemoveHapticsAndSandbox
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeStackScreens.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/HapticsDemoScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/SandboxScreen/CommonComponentWhiteList.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/SandboxScreen/PickerOptions.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/SandboxScreen/SandboxScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/waygateConfig.ts
Labels: FE-Ready to Merge

#8772 bug/8771-Binny-HSPActivity error bug
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-With QA

#8789 feature/8608-Dylan-VideoHome
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCalendarButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCancelReschedule.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentDetailsModality.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentJoinSessionPrepareForVideo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentProvider.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoHomeAppointment.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoHomeAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#8793 Create Call Center Update.md
  .github/ISSUE_TEMPLATE/Call Center Update.md
Labels: FE-With QA

#8794 Create Update App Store.md
  .github/ISSUE_TEMPLATE/Update App Store.md
Labels: FE-With QA

#8733 feature/Chika-6868-ComponentAppPropagationLink
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentDetailsScreen/PaymentDetailsScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.tsx
Labels: FE-Ready to Merge

#8808 add flaky spec docs
  VAMobile/documentation/docs/Engineering/BackEnd/Testing/Specs.md
Labels: FE-With QA

#8807 CU/7951-Dylan-UnitTestAuthServicesMock
  VAMobile/src/components/Nametag/Nametag.test.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersListScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersOverviewScreen.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.test.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/MilitaryInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.test.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.test.tsx
Labels: FE-Ready to Merge

#8716 feature/8143-theo-APICallEfficiency
  VAMobile/src/api/facilities/getFacilitiesInfo.tsx
  VAMobile/src/api/militaryService/getServiceHistory.tsx
  VAMobile/src/api/personalInformation/getPersonalInformation.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.test.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
Labels: FE-Ready to Merge

#8773 8643-Chika-IncorporateHapticsOnHomescreenErrorStates
  VAMobile/src/components/CategoryLandingAlert.tsx
Labels: FE-Ready to Merge

#8791 bug/7642-theo-ContactInfoAlert
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-Ready to Merge

#8819 feature/8687-chris-secure-message-list-date-update
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/src/components/InlineTextWithIcons.test.tsx
  VAMobile/src/components/InlineTextWithIcons.tsx
  VAMobile/src/components/MessageList.test.tsx
  VAMobile/src/components/MessageList.tsx
  VAMobile/src/utils/formattingUtils.ts
  VAMobile/src/utils/secureMessaging.tsx
Labels: FE-Ready to Merge

#8844 Enable sourcemaps for iOS
  .gitignore
  VAMobile/package.json
Labels: FE-With QA

#8800 bug/8531-theo-TextAreaCovered
  VAMobile/android/app/src/main/AndroidManifest.xml
Labels: FE-Ready to Merge

#8805 bug/8740-chris-screenreader-unread-messages
  VAMobile/src/screens/HealthScreen/HealthScreen.test.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
Labels: FE-Ready to Merge

#8818 Add Loading Indicator to Design System
  VAMobile/documentation/design/Components/Alerts and progress/LoadingIndicator.md
  VAMobile/documentation/design/intro.md
  VAMobile/documentation/docs/Flagship design library/Components/Alerts and Progress/LoadingComponent.mdx
Labels: FE-With QA

#8867 Add icon library documentation
  VAMobile/documentation/design/About/Contributing to the design system/contributing-to-the-design-system.md
  VAMobile/documentation/design/Foundation/Icons.md
Labels: FE-With QA

#8747 bug/8746-theo-LoadingAnimationGlitches
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-Ready to Merge

#8886 Added logo documentation
  VAMobile/documentation/design/Components/Alerts and progress/LoadingIndicator.md
  VAMobile/documentation/design/Foundation/Icons.md
  VAMobile/documentation/design/Foundation/Logos.md
  VAMobile/documentation/design/intro.md
Labels: FE-Ready to Merge

#8751 Automation/7184-chanel-slack-alert-when-release-build-fails
  .github/workflows/build_android.yml
  .github/workflows/on_demand_build.yml
  .github/workflows/release_build.yml
Labels: FE-With QA, FE-Changes Requested

#8899 Updated detox scripts to clear jest cache
  VAMobile/package.json
Labels: FE-Ready to Merge

#8824 bug/8598-Dylan-AndroidTextLeftAlignmentNativeActionSheets
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-Ready to Merge

#8826 Update Call Center Update.md
  .github/ISSUE_TEMPLATE/Call Center Update.md
Labels: FE-With QA

#8834 Update Update App Store.md
  .github/ISSUE_TEMPLATE/Update App Store.md
Labels: FE-With QA

#8850 Update Code-Upkeep.md
  .github/ISSUE_TEMPLATE/Code-Upkeep.md
Labels: FE-With QA

#8809 CU/8750-Dylan-PreserveWhiteSpaceSM
  VAMobile/src/store/api/demo/mocks/secureMessaging.json
  VAMobile/src/utils/secureMessaging.tsx
Labels: FE-Ready to Merge

#8894 Update Update App Store.md
  .github/ISSUE_TEMPLATE/Update App Store.md
Labels: FE-With QA

#8868 feature/8790-Dylan-CleanUpUnusedApptCode
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAlert.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAlert.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentReason.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentReason.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ClinicNameAndPhysicalLocation.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ContactInformation.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ContactInformation.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PendingAppointmentCancelButton.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PendingAppointmentCancelButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredAppointmentType.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredAppointmentType.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredDateAndTime.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredDateAndTime.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ProviderName.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ProviderName.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/TypeOfCare.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/TypeOfCare.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/CheckIn/ConfirmContactInfo.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#8820 feature/8804-theo-HSPUnitTests
  VAMobile/src/api/appointments/cancelAppointment.tsx
  VAMobile/src/api/types/AppointmentData.ts
  VAMobile/src/constants/appointments.ts
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/testUtils.tsx
  VAMobile/src/utils/tests/personalization.tsx
Labels: FE-Ready to Merge

#8801 bug/8283-theo-KeyboardCoveringActionSheet
  VAMobile/src/utils/hooks/index.tsx
Labels: FE-Ready to Merge

#8905 CU/8775-rachael-detox-update-upload-artifact-to-v4
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-Ready to Merge

#8885 feature/8702-rachael-detox-update-appointments-tests
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentCancelReschedule.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
Labels: FE-Ready to Merge

#8878 bug/8724-Dylan-AndroidTextInputAreaCursorTopLeft
  VAMobile/src/components/FormWrapper/FormFields/VATextInput.tsx
Labels: FE-Ready to Merge

#8583 Automation/6261-chanel-qa-approval-before-pr-merge
  .github/workflows/pr-checks-for-qa-approvals.yml
  .github/workflows/release_pull_request.yml
Labels: FE-With QA

#8929 bug/8911-CountAfterCancellingAppointment
  VAMobile/src/api/appointments/cancelAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
Labels: FE-Ready to Merge

#8927 Add Space Force tests in Detox
  VAMobile/e2e/tests/MilitaryInformation.e2e.ts
Labels: FE-Ready to Merge

#8903 feature/7802-Dylan-UpdateHelpPanelLinkFromButtonToLinkComponent2
  VAMobile/ios/Podfile.lock
  VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.tsx
Labels: FE-Ready to Merge

#8906 feature/6338-Dylan-RemoveCovid19UpdatesLinks
  VAMobile/documentation/docs/UX/Foundations/Information-Architecture.md
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/HealthScreen.test.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#8757 Detox/Home screen script updates for personalization TKD
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/LoginScreen.e2e.ts
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/SignIn.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
Labels: FE-Ready to Merge

#8912 Detox/8895-VeteranStatusCard-Personalization-TKD
  VAMobile/e2e/tests/VeteranStatusCard.e2e.ts
Labels: FE-Ready to Merge
