Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2024-09, with the labels that each got.

#9492 9428-Dylan-NoAppointmentsSpacing
  VAMobile/src/screens/HealthScreen/Appointments/NoAppointments/NoAppointments.tsx
Labels: FE-Ready to Merge

#9479 bug/9347-claim-details-scroll-position-fix
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimTimeline.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimTimeline.tsx
Labels: FE-Ready to Merge

#9491 bug/9307-EventTimelineNullSafety
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimPhase.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimTimeline.tsx
Labels: FE-Ready to Merge

#9513 Feature/9441 demo mode for screenreader
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9447 Automation/9431-chanel-automation-make-release-pr-branch-unique
  .github/workflows/approve_command.yml
  .github/workflows/release_pull_request.yml
Labels: FE-With QA

#9394 feature/9164-SubmitEvidence
  .github/workflows/e2e_detox_mapping.yml
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/api/claimsAndAppeals/uploadFileToClaim.tsx
  VAMobile/src/api/types/ClaimsAndAppealsData.ts
  VAMobile/src/screens/BenefitsScreen/BenefitsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/BenefitsStackScreens.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequest.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/FileRequestDetails/FileRequestDetails.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/SelectFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SubmitEvidence.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SubmitEvidence.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/TakePhotos.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/claims.tsx
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
  VAMobile/src/utils/waygateConfig.ts
Labels: FE-Ready to Merge

#9532 bug/9350-claims-list-position-screenreader-fix
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#9450 bug/9346-claim-accordion-collapse-screenreader-fix
  VAMobile/src/components/AccordionCollapsible.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#9538 Snackbar documentation
  VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
  VAMobile/documentation/docs/Flagship design library/Components/Alerts and Progress/Snackbar.md
Labels: FE-With QA, FE-Changes Requested

#9536 chore/454-RemoveDocMentionOfWhiteButtonVariant
  VAMobile/documentation/design/Components/Buttons and links/Button.md
Labels: FE-With QA

#9550 CU/9435-chanel-update-title-of-qa-approval-workflow-to-match-pattern-and-add-github-exclusion
  .github/workflows/qa_required_approvals.yml
Labels: FE-Ready to Merge

#9551 bug/9549-rachael-detox-fix-failing-AF-tests
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#9439 Doc/9438 tkd feature checklist updates
  .github/ISSUE_TEMPLATE/QA_feature_signoff.md
Labels: FE-Ready to Merge

#9496 bug/9344-MisleadingClaimDetailsAccessibilityWhyWeCombine
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ConsolidatedClaimsNote/ConsolidatedClaimsNote.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ConsolidatedClaimsNote/ConsolidatedClaimsNote.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/WhatDoIDoIfDisagreement/WhatDoIDoIfDisagreement.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/WhatDoIDoIfDisagreement/WhatDoIDoIfDisagreement.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9576 Update LoadingIndicator.md
  VAMobile/documentation/design/Components/Alerts and progress/LoadingIndicator.md
Labels: FE-With QA

#9520 feature/9423-PushNotificationScreenChanges
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/env/constant.env
  VAMobile/env/test.env.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/env.ts
Labels: FE-Ready to Merge

#9569 chore/9229-improve-vama-rx-filter-sel-event
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
Labels: FE-Ready to Merge

#8995 CU/8216-CleanUpTestIdPropsUsage
  VAMobile/src/components/AccordionCollapsible.tsx
  VAMobile/src/components/BackButton.tsx
  VAMobile/src/components/BaseListItem.tsx
  VAMobile/src/components/Carousel/CarouselTabBar.tsx
  VAMobile/src/components/CollapsibleView.tsx
  VAMobile/src/components/CommonErrorComponents/BasicError.tsx
  VAMobile/src/components/FormWrapper/FormFields/VASelector.tsx
  VAMobile/src/components/List.tsx
  VAMobile/src/components/NavigationTabBar.tsx
  VAMobile/src/components/Pagination.tsx
  VAMobile/src/components/VABulletList.tsx
  VAMobile/src/components/VAImage/VAImage.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealIssues/AppealIssues.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/TakePhotos.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimPhase.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/EstimatedDecisionDate/EstimatedDecisionDate.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/DEPRECATED_ClaimsAndAppealsListView.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppeals/NoClaimsAndAppeals.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppealsAccess/NoClaimsAndAppealsAccess.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/NoDisabilityRatings/NoDisabilityRatings.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/GenericLetter/GenericLetter.test.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/GenericLetter/GenericLetter.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersListScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/LettersOverviewScreen.tsx
  VAMobile/src/screens/BenefitsScreen/Letters/NoLettersScreen/NoLettersScreen.tsx
  VAMobile/src/screens/BiometricsPreferenceScreen/BiometricsPreferenceScreen.tsx
  VAMobile/src/screens/HealthScreen/Appointments/NoAppointments/NoAppointments.tsx
  VAMobile/src/screens/HealthScreen/Appointments/NoMatchInRecords/NoMatchInRecords.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Folders/Folders.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoInboxMessages/NoInboxMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NotEnrolledSM/NotEnrolledSM.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/TermsAndConditions/TermsAndConditions.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/NoMilitaryInformationAccess.tsx
  VAMobile/src/screens/OnboardingCarousel/GenericOnboarding/GenericOnboarding.tsx
  VAMobile/src/screens/SplashScreen/SplashScreen.tsx
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
  VAMobile/src/screens/WebviewScreen/WebviewControlButton.tsx
  VAMobile/src/screens/WebviewScreen/WebviewControls.tsx
  VAMobile/src/screens/WebviewScreen/WebviewScreen.tsx
  VAMobile/src/screens/WebviewScreen/WebviewTitle.tsx
  VAMobile/src/screens/auth/LoginScreen/LoginScreen.tsx
  VAMobile/src/utils/accessibility.tsx
Labels: FE-Ready to Merge

#9252 9061-rachael-detox-create-ticket-on-detox-nightly-build-failure
  .github/ISSUE_TEMPLATE/detox_nightly_build_failure.md
  .github/workflows/e2e_android.yml
  .github/workflows/e2e_ios.yml
Labels: FE-Ready to Merge

#9515 chore/9430-RNUpdate
  VAMobile/.detoxrc.json
  VAMobile/android/app/build.gradle
  VAMobile/android/app/src/main/AndroidManifest.xml
  VAMobile/android/app/src/main/java/gov/va/mobileapp/MainApplication.kt
  VAMobile/android/app/src/main/res/drawable/rn_edit_text_material.xml
  VAMobile/android/build.gradle
  VAMobile/android/gradle.properties
  VAMobile/android/gradle/wrapper/gradle-wrapper.properties
  VAMobile/android/settings.gradle
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/ios/Gemfile
  VAMobile/ios/Podfile
  VAMobile/ios/Podfile.lock
  VAMobile/ios/PrivacyInfo.xcprivacy
  VAMobile/ios/VAMobile.xcodeproj/project.pbxproj
  VAMobile/ios/VAMobile/AppDelegate.mm
  VAMobile/ios/VAMobile/Info.plist
  VAMobile/metro.config.js
  VAMobile/package.json
  VAMobile/src/components/Box.tsx
  VAMobile/yarn.lock
Labels: FE-Ready to Merge

#9588 chore/update-App-store-WhatsNew-2.37
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/e2e/tests/AvailabilityFramework.e2e.ts
  VAMobile/e2e/tests/Claims.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge

#9552 bug/9548-Chika-AccessibilityLabelIsStringNameInsteadOfStringNameForPayments
  VAMobile/src/App.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClosedClaimInfo/ClosedClaimStatusDetails.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/HowToUpdateDirectDepositScreen/HowToUpdateDirectDepositScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentsScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9545 CU/9419-rachael-detox-remove-in-app-reviews-from-AF
  VAMobile/e2e/tests/utils.ts
Labels: FE-Ready to Merge

#9586 Automation/9398-devops-remove-all-qa-auto-assignment-code-and-documentation
  .github/workflows/assign_qa_to_issue.yml
Labels: FE-Ready to Merge

#9608 Add documentation for spacing tokens
  VAMobile/documentation/design/Components/Buttons and links/Button.md
  VAMobile/documentation/design/Components/Buttons and links/Link.md
  VAMobile/documentation/design/Foundation/Design tokens/Color.md
  VAMobile/documentation/design/Foundation/Design tokens/Overview.md
  VAMobile/documentation/design/Foundation/Design tokens/Spacing.md
  VAMobile/documentation/design/intro.md
Labels: FE-With QA

#9600 CU/9267-chanel-Change-go-live-release-time-to-8-am
  .github/workflows/go_live.yml
Labels: FE-Ready to Merge

#9528 bug/9269-Chika-NonActionableBoxesFlaggedAsInteractiveWithVoiceControl
  VAMobile/src/components/BaseListItem.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/DetailsTextSections.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoInboxMessages/NoInboxMessages.tsx
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.tsx
Labels: FE-Ready to Merge

#9579 feature/8661-SendDeviceInfoInHeaders
  VAMobile/src/api/device/getAppVersion.tsx
  VAMobile/src/api/device/queryKeys.ts
  VAMobile/src/components/AppVersionAndBuild.tsx
  VAMobile/src/store/api/api.test.ts
  VAMobile/src/store/api/api.ts
Labels: FE-Ready to Merge

#9460 chore/5626-CrashlyticsErrorLogging
  VAMobile/documentation/docs/Operations/App metrics/Firebase.md
  VAMobile/jest/testSetup.ts
  VAMobile/src/utils/analytics.ts
Labels: FE-Ready to Merge

#9609 Added documentation around Firebase Cloud Messaging
  VAMobile/documentation/docs/Engineering/DevOps/Automation Code Docs/Signing Keys/Firebase.md
Labels: FE-With QA

#9211 Automation/6812-chanel-automation-notification-of-release-ticket-to-assign-people
  .github/workflows/release_branch_issue.yml
Labels: FE-Changes Requested, FE-Ready to Merge

#9626 chore/9616-rollback-link-with-analytics-component
  VAMobile/src/components/AttachmentLink.tsx
  VAMobile/src/components/ClickForActionLinkDeprecated.tsx
  VAMobile/src/components/LinkWithAnalytics.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/ClaimExamAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/CommunityCareAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/PhoneAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/DEPRECATED_AppointmentCalendarButton.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoAtlasAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoGFEAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoHomeAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoVAAppointment.tsx
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge

#9676 Update Resources.md
  VAMobile/documentation/docs/Engineering/DevOps/Overview.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Resources.md
Labels: FE-Ready to Merge

#9635 bug/9634-rachael-detox-sprint-106-fix-nightly-build-errors
  VAMobile/e2e/tests/HomeScreen.e2e.ts
Labels: FE-Ready to Merge

#9693 updating homescreen image to reflect HSP
  VAMobile/documentation/static/img/ios-6.5-Screen-home.png
Labels: FE-Ready to Merge

#9684 feature/9683-NotEnrolledSMAnalytic
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HealthScreen/SecureMessaging/NotEnrolledSM/NotEnrolledSM.tsx
Labels: FE-Ready to Merge

#9681 bug/9653-MessageAttachmentLoadingIndicatorFix
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.tsx
Labels: FE-Ready to Merge

#9539 bug/9471-SubmitEvidenceAccessibilityFindings
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#9662 bug/7832-UpdatePaymentsAppHeadings
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentDetailsScreen/PaymentDetailsScreen.tsx
Labels: FE-Ready to Merge

#9694 9294: document new issues monitor
  VAMobile/documentation/docs/Engineering/BackEnd/Monitoring/DataDog.md
  VAMobile/documentation/docs/Engineering/BackEnd/Monitoring/OnCallProcedure.md
Labels: FE-Ready to Merge

#9699 Update Resources.md
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Resources.md
Labels: FE-Ready to Merge

#9672 bug/9596-Chika-ChangeLinkColorInAlertToGray
  VAMobile/src/components/CommonErrorComponents/CallHelpCenter.tsx
  VAMobile/src/components/CommonErrorComponents/DowntimeError.tsx
  VAMobile/src/components/WaygateWrapper.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/TakePhotos.tsx
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionsDetailsBanner.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNoPrescriptions.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/NoVaccineRecords/NoVaccineRecords.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/NoPayments/NoPaymentsScreen.tsx
Labels: FE-Ready to Merge

#9620 CU/9578-rachael-detox-swap-out-by-text-to-by-id
  VAMobile/src/components/BaseListItem.tsx
  VAMobile/src/components/Carousel/CarouselTabBar.tsx
  VAMobile/src/components/CrisisLineButton.tsx
  VAMobile/src/components/DefaultList.tsx
  VAMobile/src/components/DescriptiveBackButton.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/PickerList.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/components/LargeNavButton.tsx
  VAMobile/src/components/MessageList.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/components/RadioGroupModal.tsx
  VAMobile/src/components/SimpleList.tsx
  VAMobile/src/components/Templates/HeaderBanner.tsx
Labels: FE-Ready to Merge

#9695 CU: 3959-retire-halfPanelCardStyleInterpolator
  VAMobile/src/utils/common.ts
Labels: FE-Ready to Merge

#9691 Automation/chanel-9375-test-auto-assign-accessibility
  .github/workflows/auto_assign_accebility_ticket.yml
Labels: accessibility, FE-With QA, FE-Changes Requested

#9711 doc-editing-doc-site-with-codespaces
  VAMobile/documentation/docs/Operations/Updating the doc site/how to update.md
Labels: FE-Ready to Merge

#9720 Automation/chanel-9375-test-new-auto-assign-accessibility
  .github/workflows/auto_assign_accebility_ticket.yml
Labels: FE-With QA

#9710 CU/9709-rachael-detox-disablity-ratings-replace-by-text
  VAMobile/e2e/tests/DisabilityRatings.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/TextArea.tsx
  VAMobile/src/screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen.tsx
Labels: FE-Ready to Merge

#9625 bug/9597-OHCopyUpdates
  VAMobile/e2e/tests/Cerner.e2e.ts
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.test.tsx
  VAMobile/src/screens/HealthScreen/CernerAlert/CernerAlert.tsx
  VAMobile/src/screens/HealthScreen/HealthHelp/HealthHelp.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/styles/themes/standardTheme.ts
  VAMobile/src/translations/en/common.json
Labels: FE-With QA, FE-Ready to Merge

#9719 Automation/9375-new-auto-assign-accessibility-ticket
  .github/workflows/auto_assign_accebility_ticket.yml
Labels: FE-With QA, FE-Ready to Merge

#9509 bug/9210-SMiOSScreenReader
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/CollapsibleMessage.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/ViewMessage/MessageCard.tsx
  VAMobile/src/utils/secureMessaging.tsx
Labels: FE-With QA, FE-Ready to Merge

#9613 feature/9168-RemoveClaimPhaseExpansionFlag
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetails/ClaimDetails.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetails/ClaimDetails.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimStatus.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimPhase.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimTimeline.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/ClaimTimeline.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimPhase.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimTimeline/DEPRECATED_ClaimTimeline.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/ClaimsAndAppealsListView.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsAndAppealsListView/DEPRECATED_ClaimsAndAppealsListView.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/utils/claims.tsx
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-With QA, FE-Ready to Merge

#9705 chore: Update "Check DD info..." Alert to align with VADS
  VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.tsx
Labels: FE-Ready to Merge

#9718 feature/9717-WebviewsIconComponentLibrary
  VAMobile/src/screens/WebviewScreen/WebviewControlButton.test.tsx
  VAMobile/src/screens/WebviewScreen/WebviewControlButton.tsx
  VAMobile/src/screens/WebviewScreen/WebviewControls.tsx
  VAMobile/src/screens/WebviewScreen/WebviewScreen.tsx
  VAMobile/src/screens/WebviewScreen/WebviewTitle.tsx
Labels: FE-Ready to Merge
