Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2025-06, with the labels that each got.

#11001 Start a claim through btsss link to use sso
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/env/constant.env
  VAMobile/env/env.sh
  VAMobile/env/test.env.ts
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/FileOnlineComponent.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#10906 Chore/6807 apply milestone
  .github/test-data/pull_request
  .github/workflows/apply-milestone.yml
Labels: FE-Ready to Merge

#11017 adding the auto close of the milestone
  .github/workflows/release_branch_issue.yml
Labels: FE-Ready to Merge

#11010 Update Upstream Services Map
  VAMobile/documentation/README.md
  VAMobile/documentation/docs/Engineering/BackEnd/Architecture/Services.md
  VAMobile/documentation/static/img/backend/upstream-service-map.png
  VAMobile/documentation/yarn.lock
  VAMobile/package.json
Labels: FE-Ready to Merge, FE-Changes Requested

#11055 fixing approve command flow
  .github/workflows/approve_command.yml
Labels: FE-Ready to Merge, no-issue

#11072 Removed unused add-user-to-team.yml issue template
  .github/ISSUE_TEMPLATE/add-user-to-team.yml
Labels: FE-With QA, no-issue

#11105 Set devops as workflow codeowners
  .github/CODEOWNERS
Labels: no-issue

#11132 removed empty element when using screen reader
  VAMobile/src/components/Templates/FeatureLandingAndChildTemplate.tsx
Labels: FE-With QA

#11169 comment out update ticket until its fixed
  .github/workflows/release_branch_issue.yml
Labels: no-issue

#11027 10872 Update various relative paths to absolute paths
  VAMobile/src/components/Carousel/Carousel.test.tsx
  VAMobile/src/components/Carousel/Carousel.tsx
  VAMobile/src/components/Carousel/CarouselTabBar.test.tsx
  VAMobile/src/components/Carousel/CarouselTabBar.tsx
  VAMobile/src/components/ClickForActionLinkDeprecated.test.tsx
  VAMobile/src/components/ClickForActionLinkDeprecated.tsx
  VAMobile/src/components/CollapsibleView.test.tsx
  VAMobile/src/components/CollapsibleView.tsx
  VAMobile/src/components/CommonErrorComponents/BasicError.test.tsx
  VAMobile/src/components/CommonErrorComponents/CallHelpCenter.test.tsx
  VAMobile/src/components/CommonErrorComponents/CustomError.test.tsx
Labels: FE-With QA, no-issue

#11109 Feature/111280 binny travel pay activity button
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/src/api/travelPay/submitClaim.tsx
  VAMobile/src/api/types/AppointmentData.ts
  VAMobile/src/components/ActivityButton.tsx
  VAMobile/src/constants/linking.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.test.tsx
  VAMobile/src/screens/HealthScreen/HealthScreen.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/tests/personalization.tsx
Labels: FE-With QA

#11214 update automation ticket
  .github/ISSUE_TEMPLATE/detox_nightly_build_failure.md
Labels: no-issue
