Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2025-04, with the labels that each got.

#10624 fix: update links within appeal to annouce properly in voice over/tal…
  VAMobile/.detoxrc.json
  VAMobile/src/components/VABulletList.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10451 Update Allergy and Vaccine screens based on demo feedback
  VAMobile/e2e/tests/Allergies.e2e.ts
  VAMobile/e2e/tests/Navigation.e2e.ts
  VAMobile/e2e/tests/VaccineRecords.e2e.ts
  VAMobile/package.json
  VAMobile/src/screens/HealthScreen/Allergies/AllergyDetails/AllergyDetailsScreen.test.tsx
  VAMobile/src/screens/HealthScreen/Allergies/AllergyDetails/AllergyDetailsScreen.tsx
  VAMobile/src/screens/HealthScreen/Allergies/AllergyList/AllergyListScreen.tsx
  VAMobile/src/screens/HealthScreen/MedicalRecordsScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/NoVaccineRecords/NoVaccineRecords.test.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineDetails/VaccineDetailsScreen.tsx
  VAMobile/src/screens/HealthScreen/Vaccines/VaccineList/VaccineListScreen.tsx
  VAMobile/src/store/api/demo/mocks/vaccine.json
  VAMobile/src/translations/en/common.json
Labels: FE-With QA, FE-Changes Requested

#10637 Android/Samsung - VA pronunciation on Rx error screen
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoAccessSM/NoAccessSM.tsx
Labels: FE-Ready to Merge

#10639 Add alternate paths
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/NotEligibleTypeScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/FileOnlineComponent.tsx
Labels: FE-With QA

#10383 bug/10330-emptyPageAfterMovingMessage
  VAMobile/src/screens/HealthScreen/SecureMessaging/FolderMessages/FolderMessages.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/Inbox/Inbox.tsx
Labels: FE-Ready to Merge

#10661 [MFS] Veteran Status API Change // Error Surfacing
  VAMobile/src/api/types/index.ts
  VAMobile/src/components/MilitaryBranchEmblem.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/components/VAIcon/svgs/VASeal.svg
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.test.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/store/api/demo/mocks/profile.json
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge, no-issue

#10679 feature/10678-Binny-VSC-Error-Analytics
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
Labels: FE-Ready to Merge

#10660 feat: Update copy text for Rx refill phone number link
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetailsBanner.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionsDetailsBanner.tsx
Labels: FE-Ready to Merge

#10648 Task 10609 - Remove bold from alerts
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoAccessSM/NoAccessSM.tsx
Labels: FE-Ready to Merge

#10638 updated primaryTextColor to vadsColorBase to match designs
  VAMobile/src/styles/themes/colorSchemes.ts
Labels: FE-Ready to Merge

#10686 feature/10558-Remove-Endpoint-Call
  VAMobile/src/screens/SyncScreen/SyncScreen.tsx
Labels: FE-Ready to Merge

#10697 skipping broken detox test to clear CI
  VAMobile/e2e/tests/VALetters.e2e.ts
Labels: FE-With QA, no-issue

#10698 Moving the skipped test
  VAMobile/e2e/tests/VALetters.e2e.ts
Labels: FE-With QA, no-issue

#10699 Adding release notes
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
Labels: FE-With QA, no-issue

#10664 Show and hide compensation and disability rating
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/components/ObfuscatedTextView.tsx
  VAMobile/src/components/index.ts
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/colorSchemes.ts
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10623 chore/284-FixDemoPasswordEntryForLocalE2ETests
  VAMobile/src/screens/auth/LoginScreen/DemoAlert.tsx
Labels: FE-Ready to Merge, no-issue

#10711 Chore updating skip for VALetters for e2e testing
  VAMobile/e2e/tests/VALetters.e2e.ts
Labels: FE-Ready to Merge, no-issue

#10659 Travel Pay - Add remote config
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentFileTravelPayAlert.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/utils/appointments.tsx
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-With QA, FE-Changes Requested

#10730 Removing inaccessible documentation
  VAMobile/documentation/docs/QA/QualityAssuranceProcess/Resources.md
Labels: FE-With QA, no-issue

#10731 Update pull_request_template.md
  .github/pull_request_template.md
Labels: no-issue

#10710 SSO MVP Enabled
  VAMobile/e2e/tests/Appeals.e2e.ts
  VAMobile/env/constant.env
  VAMobile/env/env.sh
  VAMobile/env/test.env.ts
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData.test.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData.tsx
  VAMobile/src/screens/HealthScreen/Appointments/NoAppointments/NoAppointments.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.tsx
  VAMobile/src/screens/WebviewScreen/WebviewScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge

#10708 [MFS] Veteran Status Card Redesign
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/VeteranStatusCard.e2e.ts
  VAMobile/src/components/MilitaryBranchEmblem.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/components/VAIcon/VAIcon.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusCard/VeteranStatusCard.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.test.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/styles/theme.ts
  VAMobile/src/styles/themes/standardTheme.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-With QA, FE-Changes Requested, no-issue

#10765 Adding release notes
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
Labels: no-issue

#10737 BUG 10325 - Missing photo/file voiceover fix and swipe
  VAMobile/src/components/PhotoAdd.test.tsx
  VAMobile/src/components/PhotoAdd.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.tsx
Labels: FE-Ready to Merge

#10771 431 - Adding null checking for veteranStatusConfirmed & getVeteranStatus
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
Labels: FE-With QA, no-issue

#10764 Convert to Mobile multi-step subtask
  VAMobile/e2e/detoxMapping.json
  VAMobile/src/api/travelPay/index.ts
  VAMobile/src/api/travelPay/submitClaim.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/AddressScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ErrorScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/InterstitialScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/MileageScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/SubmitSuccessScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/SubmitSuccessScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/VehicleScreen.tsx
Labels: FE-With QA

#10598 Share My Health Data App Link
  VAMobile/env/constant.env
  VAMobile/env/test.env.ts
  VAMobile/src/components/MilitaryBranchEmblem.tsx
  VAMobile/src/screens/HealthScreen/MedicalRecordsScreen.test.tsx
  VAMobile/src/screens/HealthScreen/MedicalRecordsScreen.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/env.ts
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge, FE-Changes Requested, Do not merge

#10790 10757 Enable submit evidence by default
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-Ready to Merge
