Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2025-05, with the labels that each got.

#10763 BUG 10415 - Date filter for appointments in demo mode
  VAMobile/e2e/tests/Appointments.e2e.ts
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/src/store/api/demo/appointments.ts
  VAMobile/src/store/api/demo/mocks/appointments.json
Labels: FE-With QA

#10805 Travel pay/claims flag for appt
  VAMobile/src/api/appointments/getAppointments.tsx
  VAMobile/src/api/types/AppointmentData.ts
  VAMobile/src/api/types/TravelPayClaimData.ts
  VAMobile/src/store/api/demo/mocks/appointments.json
Labels: FE-With QA

#10748 Feature/10689 payment breakdown modal
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/e2e/tests/Payments.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/components/Box.tsx
  VAMobile/src/components/DefaultList.tsx
  VAMobile/src/components/List.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/PaymentBreakdownModal/PaymentBreakdownModal.test.tsx
  VAMobile/src/screens/HomeScreen/PaymentBreakdownModal/PaymentBreakdownModal.tsx
  VAMobile/src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.test.tsx
  VAMobile/src/store/api/demo/mocks/payments.json
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/formattingUtils.ts
  VAMobile/src/utils/payments.tsx
Labels: FE-With QA, FE-Changes Requested

#10835 feature/10834-Binny-ReduceEventLoad
  VAMobile/src/App.tsx
  VAMobile/src/components/AccordionCollapsible.tsx
  VAMobile/src/components/FormWrapper/FormFields/Picker/VAModalPicker.tsx
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimDetailsScreen.tsx
  VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimsHistoryScreen/ClaimsHistoryScreen.tsx
  VAMobile/src/screens/HealthScreen/Appointments/Appointments.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/store/slices/authSlice.ts
Labels: FE-Ready to Merge

#10840 upgrade ruby to 3.1
  .github/workflows/build_android.yml
  .github/workflows/e2e_android.yml
Labels: FE-With QA, no-issue

#10811 Add travel pay details component
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/env/env.sh
  VAMobile/env/test.env.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/ClaimExamAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/CommunityCareAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/PhoneAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoAtlasAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoGFEAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoHomeAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/VideoVAAppointment.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/TravelPayHelp.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/TravelPayHelp.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/appointments.tsx
  VAMobile/src/utils/env.ts
Labels: FE-Changes Requested

#10837 Chore/10804 bump chrome driver
  .github/workflows/documentation_accessibility_checks.yml
  VAMobile/documentation/yarn.lock
Labels: devops, FE-Ready to Merge

#10854 Fix Failing Detox Build
  .github/workflows/e2e_android.yml
Labels: FE-With QA

#10833 107847 claim not filed
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/translations/en/common.json
Labels: FE-With QA, FE-Changes Requested

#10776 108370 pass attributes for submission
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/src/api/travelPay/submitClaim.tsx
  VAMobile/src/api/types/AppointmentData.ts
  VAMobile/src/api/types/TravelPayClaimData.ts
  VAMobile/src/api/types/index.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentFileTravelPayAlert.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentFileTravelPayAlert.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ErrorScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/SubmitSuccessScreen.tsx
  VAMobile/src/store/api/demo/store.ts
  VAMobile/src/store/api/demo/travelPay.ts
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/travelPay.tsx
Labels: FE-With QA

#10861 Fix documentation site search function
  VAMobile/documentation/package.json
  VAMobile/documentation/src/theme/SearchBar/DocSearch.js
  VAMobile/documentation/src/theme/SearchBar/algolia.css
  VAMobile/documentation/src/theme/SearchBar/index.js
  VAMobile/documentation/src/theme/SearchBar/lib/DocSearch.js
  VAMobile/documentation/src/theme/SearchBar/lib/lunar-search.js
  VAMobile/documentation/src/theme/SearchBar/lib/templates.js
  VAMobile/documentation/src/theme/SearchBar/lib/utils.js
  VAMobile/documentation/src/theme/SearchBar/lunar-search.js
  VAMobile/documentation/src/theme/SearchBar/styles.css
  VAMobile/documentation/src/theme/SearchBar/templates.js
  VAMobile/documentation/src/theme/SearchBar/utils.js
  VAMobile/documentation/yarn.lock
Labels: FE-With QA

#10881 Add Jest Reporter for slow tests
  VAMobile/jest.config.js
  VAMobile/package.json
  VAMobile/yarn.lock
Labels: FE-With QA, no-issue

#10704 Bug 9629 - Add error state to contact and personal screen
  VAMobile/src/constants/analytics.ts
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/ContactInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.test.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#10863 Claim Submission follow up
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/src/api/travelPay/submitClaim.tsx
  VAMobile/src/api/types/TravelPayClaimData.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentFileTravelPayAlert.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentFileTravelPayAlert.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/screens/HealthScreen/HealthStackScreens.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/utils/travelPay.tsx
Labels: FE-With QA

#10893 Travel Pay / add claim retrieval error messaging
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10905 Remove appointment ID from params
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/src/api/travelPay/submitClaim.tsx
  VAMobile/src/api/types/TravelPayClaimData.ts
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
Labels: FE-With QA

#10907 Adding document for using act
  VAMobile/documentation/docs/Engineering/DevOps/AutomationCodeDocs/GitHubActions/UsingActWithActions.md
Labels: devops, FE-Ready to Merge, no-issue

#10627 Chore/10541 release approval process
  .github/workflows/approve_command.yml
  .github/workflows/new_release_branch.yml
  .github/workflows/release_branch_issue.yml
  VAMobile/documentation/docs/Operations/Releases/release-process.md
  VAMobile/documentation/docusaurus.config.js
  VAMobile/documentation/static/img/release/va-mobile-release-process.png
  VAMobile/documentation/yarn.lock
  VAMobile/src/utils/remoteConfig.ts
  yarn.lock
Labels: FE-Ready to Merge

#10918 Travel pay / Update submit claim response to include attributes
  VAMobile/src/api/travelPay/submitClaim.tsx
  VAMobile/src/api/types/TravelPayClaimData.ts
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/store/api/demo/travelPay.ts
Labels: FE-With QA

#10917 Added component to documentation to generate full release report
  .github/workflows/documentation_deploy.yml
  .github/workflows/documentation_test_build.yml
  .gitignore
  VAMobile/documentation/docs/Operations/Releases/release-report.mdx
  VAMobile/documentation/package.json
  VAMobile/documentation/src/components/ReleaseReport.tsx
  VAMobile/documentation/tsconfig.json
  VAMobile/documentation/utils/fetchGitHubData.js
  VAMobile/documentation/yarn.lock
Labels: FE-With QA, no-issue

#10921 Update release_branch_issue.yml
  .github/workflows/release_branch_issue.yml
Labels: FE-With QA, no-issue

#10904 Update address link
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/AddressScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ErrorScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ErrorScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/VehicleScreen.tsx
Labels: FE-With QA

#10936 Revert "Chore/10541 release approval process"
  .github/workflows/approve_command.yml
  .github/workflows/new_release_branch.yml
  .github/workflows/release_branch_issue.yml
  VAMobile/documentation/docs/Operations/Releases/release-process.md
  VAMobile/documentation/docusaurus.config.js
  VAMobile/documentation/static/img/release/va-mobile-release-process.png
  VAMobile/src/utils/remoteConfig.ts
  yarn.lock
Labels: FE-Ready to Merge, no-issue

#10939 109916 mobile verify and add e2e tests as necessary
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/OverrideApiScreen.tsx
  VAMobile/src/screens/WebviewScreen/WebviewScreen.tsx
Labels: FE-With QA

#10940 updated copy for MessageList read receipt tag
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/src/components/MessageList.test.tsx
  VAMobile/src/components/MessageList.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge, no-issue

#10943 Travel pay / Update translations file
  VAMobile/src/constants/linking.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/BurdenStatement.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#10919 Fixes keyboard nav for large panels
  VAMobile/e2e/tests/PersonalInformationScreen.e2e.ts
  VAMobile/e2e/tests/SettingsScreen.e2e.ts
  VAMobile/e2e/tests/VeteranStatusCard.e2e.ts
  VAMobile/src/components/Templates/LargePanel.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.tsx
Labels: FE-Ready to Merge

#10960 Task/travel pay smoc improvements
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentTravelClaimDetails.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/AddressScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/MileageScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/VehicleScreen.tsx
  VAMobile/src/utils/travelPay.tsx
Labels: FE-With QA

#10964 Tweak vama_vsc_error_shown event handling
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
Labels: FE-With QA, no-issue

#10982 499 - Revisiting Nametag component visibility (VSC)
  VAMobile/src/components/Nametag/Nametag.test.tsx
  VAMobile/src/components/Nametag/Nametag.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
Labels: FE-With QA, no-issue

#10973 Chore/10541 release approval process
  .github/workflows/approve_command.yml
  .github/workflows/release_branch_issue.yml
Labels: FE-Ready to Merge
