Repository department-of-veterans-affairs/va-mobile-app, pull requests merged in 2025-03, with the labels that each got.

#10480 254 - Endpoint Configuration for vet_verification_status
  VAMobile/src/api/types/VeteranVerificationStatusPayload.ts
  VAMobile/src/api/types/index.ts
  VAMobile/src/api/veteranStatus/getVeteranStatus.tsx
  VAMobile/src/api/veteranStatus/index.ts
  VAMobile/src/api/veteranStatus/queryKeys.ts
Labels: FE-With QA

#10488 Update release calendar
  VAMobile/documentation/docs/Operations/Releases/index.md
Labels: FE-With QA

#10493 281 - Configure console warnings locally
  VAMobile/src/App.tsx
  VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/DeveloperScreen.tsx
  VAMobile/src/utils/consoleWarnings.ts
Labels: FE-Ready to Merge

#10508 Feature toggle for allergies
  VAMobile/src/screens/HealthScreen/MedicalRecordsScreen.test.tsx
  VAMobile/src/screens/HealthScreen/MedicalRecordsScreen.tsx
  VAMobile/src/utils/remoteConfig.test.ts
  VAMobile/src/utils/remoteConfig.ts
Labels: FE-With QA, FE-Ready to Merge

#10497 Updating automation for current mobile team
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/release_ticket.md
  .github/workflows/release_branch_issue.yml
Labels: FE-With QA

#10448 Adding non-urgent message alert to secure messaging form
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#10512 Update feature-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: FE-With QA

#10506 Feature/259 VSC catch all error
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusError/VeteranStatusError.test.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusError/VeteranStatusError.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/store/api/demo/mocks/profile.json
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#10539 Removing e2e test for urgent message link that was removed
  VAMobile/e2e/tests/Messages.e2e.ts
Labels: FE-With QA

#10538 Updating Release issues steps.
  VAMobile/documentation/docs/Engineering/DevOps/Automation Code Docs/GitHub Actions/ReleaseIssues.md
Labels: FE-Ready to Merge

#10544 2 46 release
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
Labels: FE-With QA

#10550 Revert "Adding non-urgent message alert to secure messaging form"
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10561 Update release_ticket.md
  .github/ISSUE_TEMPLATE/release_ticket.md
Labels: FE-With QA

#10481 Add travel pay entry point
  VAMobile/src/api/types/AppointmentData.ts
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/InPersonVAAppointment.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentFileTravelPayAlert.test.tsx
  VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentFileTravelPayAlert.tsx
  VAMobile/src/screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails.tsx
  VAMobile/src/store/api/demo/mocks/appointments.json
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/appointments.tsx
Labels: FE-With QA

#10560 Adding non-urgent message alert to secure messaging form
  VAMobile/e2e/tests/Messages.e2e.ts
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA

#10574 Updated tj-actions/changed-files due to security issue
  .github/workflows/e2e_detox_mapping.yml
Labels: FE-With QA

#10551 Add other two errors to VeteranStatusCard
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusError/VeteranStatusError.test.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusError/VeteranStatusError.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.test.tsx
  VAMobile/src/screens/HomeScreen/VeteranStatusScreen/VeteranStatusScreen.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA, FE-Changes Requested

#10575 Enable all users to view veteran status card
  VAMobile/src/components/Nametag/Nametag.tsx
Labels: FE-With QA

#10580 Update feature-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: FE-With QA

#10590 10558-Update-Homescreen-Compensation
  VAMobile/e2e/tests/HomeScreen.e2e.ts
  VAMobile/src/api/types/PaymentData.ts
  VAMobile/src/screens/HomeScreen/HomeScreen.test.tsx
  VAMobile/src/screens/HomeScreen/HomeScreen.tsx
  VAMobile/src/store/api/demo/mocks/payments.json
  VAMobile/src/translations/en/common.json
Labels: FE-Ready to Merge

#10562 Update content for error states in rx and secure messaging
  VAMobile/env/constant.env
  VAMobile/env/test.env.ts
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized.test.tsx
  VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoAccessSM/NoAccessSM.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NoAccessSM/NoAccessSM.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/NotEnrolledSM/NotEnrolledSM.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.test.tsx
  VAMobile/src/screens/HealthScreen/SecureMessaging/SecureMessaging.tsx
  VAMobile/src/translations/en/common.json
  VAMobile/src/utils/env.ts
Labels: FE-Ready to Merge, FE-Changes Requested

#10507 Add tests for Travel Pay Part 2
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ErrorScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/NotEligibleTypeScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/SubmitSuccessScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/FileOnlineComponent.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/TravelPayHelp.tsx
  VAMobile/src/translations/en/common.json
Labels: FE-With QA, FE-Changes Requested

#10559 Add tests for wrapper
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.tsx
Labels: FE-With QA

#10543 Add Tests for Travel Pay components
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/FileOnlineComponent.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/TravelPayHelp.test.tsx
Labels: FE-With QA

#10597 10549-Binny-UpdateIOSSDK
  .github/workflows/build_ios.yml
  .github/workflows/e2e_ios.yml
  VAMobile/.detoxrc.json
  VAMobile/ios/VAMobile.xcodeproj/project.pbxproj
Labels: FE-Ready to Merge

#10613 Add new team to approvals
  .github/CODEOWNERS
  .github/workflows/label_pull_request_onReview.yml
  .github/workflows/qa_required_approvals.yml
Labels: FE-With QA

#10600 10533 - Medical Records VA.gov pronunciation
  VAMobile/src/screens/HealthScreen/MedicalRecordsScreen.tsx
Labels: FE-Ready to Merge

#10622 Updating the set-output command
  .github/workflows/create_testrail_milestone.yml
  .github/workflows/go_live.yml
  .github/workflows/new_release_branch.yml
  .github/workflows/release_pull_request.yml
  .github/workflows/start_test_rail_run.yml
Labels: FE-Ready to Merge

#10625 feature/10549-Binny-SDKUpdate2
  .github/workflows/build_ios.yml
  .github/workflows/e2e_ios.yml
  VAMobile/ios/fastlane/Fastfile
Labels: FE-Ready to Merge

#10596 103595 add e2e test for submit travel pay flow happy path
  VAMobile/e2e/detoxMapping.json
  VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
  VAMobile/e2e/tests/ContactInformation.e2e.ts
  VAMobile/e2e/tests/TravelPay.e2e.ts
  VAMobile/e2e/tests/utils.ts
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.test.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitMileageTravelPayScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/AddressScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/MileageScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/ReviewClaimScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/SubmitSuccessScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/VehicleScreen.tsx
  VAMobile/src/screens/HealthScreen/TravelPay/SubmitTravelPayFlowSteps/components/TravelPayHelp.tsx
Labels: FE-With QA

#10641 Feature/2.4.7 release notes
  VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt
  VAMobile/ios/fastlane/metadata/en-US/release_notes.txt
Labels: FE-Ready to Merge
